// This file is generated with "update_icon_font.py" from FontAwesome's metadata.

// List of method calls for IconSelectDialog.
addIcon(0xf2b9, false, QStringList() << "address book");
addIcon(0xf2bb, false, QStringList() << "address card");
addIcon(0xf042, false, QStringList() << "adjust" << "contrast");
addIcon(0xf037, false, QStringList() << "align-center" << "middle" << "text");
addIcon(0xf039, false, QStringList() << "align-justify" << "text");
addIcon(0xf036, false, QStringList() << "align-left" << "text");
addIcon(0xf038, false, QStringList() << "align-right" << "text");
addIcon(0xf0f9, false, QStringList() << "ambulance" << "vehicle" << "support" << "help");
addIcon(0xf2a3, false, QStringList() << "american sign language interpreting");
addIcon(0xf13d, false, QStringList() << "anchor" << "link");
addIcon(0xf103, false, QStringList() << "angle double down" << "arrows");
addIcon(0xf100, false, QStringList() << "angle double left" << "laquo" << "quote" << "previous" << "back" << "arrows");
addIcon(0xf101, false, QStringList() << "angle double right" << "raquo" << "quote" << "next" << "forward" << "arrows");
addIcon(0xf102, false, QStringList() << "angle double up" << "arrows");
addIcon(0xf107, false, QStringList() << "angle-down" << "arrow");
addIcon(0xf104, false, QStringList() << "angle-left" << "previous" << "back" << "arrow");
addIcon(0xf105, false, QStringList() << "angle-right" << "next" << "forward" << "arrow");
addIcon(0xf106, false, QStringList() << "angle-up" << "arrow");
addIcon(0xf187, false, QStringList() << "archive" << "box" << "storage");
addIcon(0xf358, false, QStringList() << "alternate arrow circle down" << "download" << "arrow-circle-o-down");
addIcon(0xf359, false, QStringList() << "alternate arrow circle left" << "previous" << "back" << "arrow-circle-o-left");
addIcon(0xf35a, false, QStringList() << "alternate arrow circle right" << "next" << "forward" << "arrow-circle-o-right");
addIcon(0xf35b, false, QStringList() << "alternate arrow circle up" << "arrow-circle-o-up");
addIcon(0xf0ab, false, QStringList() << "arrow circle down" << "download");
addIcon(0xf0a8, false, QStringList() << "arrow circle left" << "previous" << "back");
addIcon(0xf0a9, false, QStringList() << "arrow circle right" << "next" << "forward");
addIcon(0xf0aa, false, QStringList() << "arrow circle up");
addIcon(0xf063, false, QStringList() << "arrow-down" << "download");
addIcon(0xf060, false, QStringList() << "arrow-left" << "previous" << "back");
addIcon(0xf061, false, QStringList() << "arrow-right" << "next" << "forward");
addIcon(0xf062, false, QStringList() << "arrow-up");
addIcon(0xf0b2, false, QStringList() << "alternate arrows" << "expand" << "enlarge" << "fullscreen" << "bigger" << "move" << "reorder" << "resize" << "arrow" << "arrows");
addIcon(0xf337, false, QStringList() << "alternate arrows horizontal" << "resize" << "arrows-h");
addIcon(0xf338, false, QStringList() << "alternate arrows vertical" << "resize" << "arrows-v");
addIcon(0xf2a2, false, QStringList() << "assistive listening systems");
addIcon(0xf069, false, QStringList() << "asterisk" << "details");
addIcon(0xf1fa, false, QStringList() << "at" << "email" << "e-mail");
addIcon(0xf29e, false, QStringList() << "audio description");
addIcon(0xf04a, false, QStringList() << "backward" << "rewind" << "previous");
addIcon(0xf24e, false, QStringList() << "balance scale");
addIcon(0xf05e, false, QStringList() << "ban" << "delete" << "remove" << "trash" << "hide" << "block" << "stop" << "abort" << "cancel");
addIcon(0xf02a, false, QStringList() << "barcode" << "scan");
addIcon(0xf0c9, false, QStringList() << "bars" << "menu" << "drag" << "reorder" << "settings" << "list" << "ul" << "ol" << "checklist" << "todo" << "list" << "hamburger");
addIcon(0xf2cd, false, QStringList() << "bath");
addIcon(0xf244, false, QStringList() << "battery empty" << "power");
addIcon(0xf240, false, QStringList() << "battery full" << "power");
addIcon(0xf242, false, QStringList() << "battery 1/2 full" << "power");
addIcon(0xf243, false, QStringList() << "battery 1/4 full" << "power");
addIcon(0xf241, false, QStringList() << "battery 3/4 full" << "power");
addIcon(0xf236, false, QStringList() << "bed" << "travel");
addIcon(0xf0fc, false, QStringList() << "beer" << "alcohol" << "stein" << "drink" << "mug" << "bar" << "liquor");
addIcon(0xf0f3, false, QStringList() << "bell" << "alert" << "reminder" << "notification");
addIcon(0xf1f6, false, QStringList() << "bell slash");
addIcon(0xf206, false, QStringList() << "bicycle" << "vehicle" << "bike");
addIcon(0xf1e5, false, QStringList() << "binoculars");
addIcon(0xf1fd, false, QStringList() << "birthday cake");
addIcon(0xf29d, false, QStringList() << "blind");
addIcon(0xf032, false, QStringList() << "bold");
addIcon(0xf0e7, false, QStringList() << "lightning bolt" << "lightning" << "weather");
addIcon(0xf1e2, false, QStringList() << "bomb");
addIcon(0xf02d, false, QStringList() << "book" << "read" << "documentation");
addIcon(0xf02e, false, QStringList() << "bookmark" << "save");
addIcon(0xf2a1, false, QStringList() << "braille");
addIcon(0xf0b1, false, QStringList() << "briefcase" << "work" << "business" << "office" << "luggage" << "bag");
addIcon(0xf188, false, QStringList() << "bug" << "report" << "insect");
addIcon(0xf1ad, false, QStringList() << "building" << "work" << "business" << "apartment" << "office" << "company");
addIcon(0xf0a1, false, QStringList() << "bullhorn" << "announcement" << "share" << "broadcast" << "louder" << "megaphone");
addIcon(0xf140, false, QStringList() << "bullseye" << "target");
addIcon(0xf207, false, QStringList() << "bus" << "vehicle");
addIcon(0xf1ec, false, QStringList() << "calculator");
addIcon(0xf133, false, QStringList() << "calendar" << "date" << "time" << "when" << "event" << "calendar-o");
addIcon(0xf073, false, QStringList() << "alternate calendar" << "date" << "time" << "when" << "event" << "calendar");
addIcon(0xf274, false, QStringList() << "calendar check" << "ok");
addIcon(0xf272, false, QStringList() << "calendar minus");
addIcon(0xf271, false, QStringList() << "calendar plus");
addIcon(0xf273, false, QStringList() << "calendar times");
addIcon(0xf030, false, QStringList() << "camera" << "photo" << "picture" << "record");
addIcon(0xf083, false, QStringList() << "retro camera" << "photo" << "picture" << "record");
addIcon(0xf1b9, false, QStringList() << "car" << "vehicle");
addIcon(0xf0d7, false, QStringList() << "caret down" << "more" << "dropdown" << "menu" << "triangle down" << "arrow");
addIcon(0xf0d9, false, QStringList() << "caret left" << "previous" << "back" << "triangle left" << "arrow");
addIcon(0xf0da, false, QStringList() << "caret right" << "next" << "forward" << "triangle right" << "arrow");
addIcon(0xf150, false, QStringList() << "caret square down" << "more" << "dropdown" << "menu" << "caret-square-o-down");
addIcon(0xf191, false, QStringList() << "caret square left" << "previous" << "back" << "caret-square-o-left");
addIcon(0xf152, false, QStringList() << "caret square right" << "next" << "forward" << "caret-square-o-right");
addIcon(0xf151, false, QStringList() << "caret square up" << "caret-square-o-up");
addIcon(0xf0d8, false, QStringList() << "caret up" << "triangle up" << "arrow");
addIcon(0xf218, false, QStringList() << "shopping cart arrow down" << "shopping");
addIcon(0xf217, false, QStringList() << "add to shopping cart" << "add" << "shopping");
addIcon(0xf0a3, false, QStringList() << "certificate" << "badge" << "star");
addIcon(0xf1fe, false, QStringList() << "area chart" << "graph" << "analytics" << "area-chart");
addIcon(0xf080, false, QStringList() << "bar chart" << "graph" << "analytics" << "bar-chart");
addIcon(0xf201, false, QStringList() << "line chart" << "graph" << "analytics" << "line-chart");
addIcon(0xf200, false, QStringList() << "pie chart" << "graph" << "analytics" << "pie-chart");
addIcon(0xf00c, false, QStringList() << "check" << "checkmark" << "done" << "todo" << "agree" << "accept" << "confirm" << "tick" << "ok");
addIcon(0xf058, false, QStringList() << "check circle" << "todo" << "done" << "agree" << "accept" << "confirm" << "ok");
addIcon(0xf14a, false, QStringList() << "check square" << "checkmark" << "done" << "todo" << "agree" << "accept" << "confirm" << "ok");
addIcon(0xf13a, false, QStringList() << "chevron circle down" << "more" << "dropdown" << "menu" << "arrow");
addIcon(0xf137, false, QStringList() << "chevron circle left" << "previous" << "back" << "arrow");
addIcon(0xf138, false, QStringList() << "chevron circle right" << "next" << "forward" << "arrow");
addIcon(0xf139, false, QStringList() << "chevron circle up" << "arrow");
addIcon(0xf078, false, QStringList() << "chevron-down");
addIcon(0xf053, false, QStringList() << "chevron-left" << "bracket" << "previous" << "back");
addIcon(0xf054, false, QStringList() << "chevron-right" << "bracket" << "next" << "forward");
addIcon(0xf077, false, QStringList() << "chevron-up");
addIcon(0xf1ae, false, QStringList() << "child");
addIcon(0xf111, false, QStringList() << "circle" << "dot" << "notification" << "circle-thin");
addIcon(0xf1ce, false, QStringList() << "circle notched" << "circle-o-notch");
addIcon(0xf328, false, QStringList() << "clipboard" << "paste");
addIcon(0xf017, false, QStringList() << "clock" << "watch" << "timer" << "late" << "timestamp" << "date");
addIcon(0xf24d, false, QStringList() << "clone" << "copy");
addIcon(0xf20a, false, QStringList() << "closed captioning" << "cc");
addIcon(0xf0c2, false, QStringList() << "cloud" << "save");
addIcon(0xf381, false, QStringList() << "cloud download-alt" << "cloud-download");
addIcon(0xf382, false, QStringList() << "cloud upload-alt" << "cloud-upload");
addIcon(0xf121, false, QStringList() << "code" << "html" << "brackets");
addIcon(0xf126, false, QStringList() << "code branch" << "git" << "fork" << "vcs" << "svn" << "github" << "rebase" << "version" << "branch" << "code-fork");
addIcon(0xf0f4, false, QStringList() << "coffee" << "morning" << "mug" << "breakfast" << "tea" << "drink" << "cafe");
addIcon(0xf013, false, QStringList() << "cog" << "settings");
addIcon(0xf085, false, QStringList() << "cogs" << "settings");
addIcon(0xf0db, false, QStringList() << "columns" << "split" << "panes");
addIcon(0xf075, false, QStringList() << "comment" << "speech" << "notification" << "note" << "chat" << "bubble" << "feedback" << "message" << "texting" << "sms" << "conversation");
addIcon(0xf27a, false, QStringList() << "alternate comment" << "speech" << "notification" << "note" << "chat" << "bubble" << "feedback" << "message" << "texting" << "sms" << "conversation" << "commenting" << "commenting");
addIcon(0xf086, false, QStringList() << "comments" << "speech" << "notification" << "note" << "chat" << "bubble" << "feedback" << "message" << "texting" << "sms" << "conversation");
addIcon(0xf14e, false, QStringList() << "compass" << "safari" << "directory" << "menu" << "location");
addIcon(0xf066, false, QStringList() << "compress" << "collapse" << "combine" << "contract" << "merge" << "smaller");
addIcon(0xf0c5, false, QStringList() << "copy" << "duplicate" << "clone" << "file" << "files-o");
addIcon(0xf1f9, false, QStringList() << "copyright");
addIcon(0xf09d, false, QStringList() << "credit card" << "money" << "buy" << "debit" << "checkout" << "purchase" << "payment" << "credit-card-alt");
addIcon(0xf125, false, QStringList() << "crop");
addIcon(0xf05b, false, QStringList() << "crosshairs" << "picker");
addIcon(0xf1b2, false, QStringList() << "cube");
addIcon(0xf1b3, false, QStringList() << "cubes");
addIcon(0xf0c4, false, QStringList() << "cut" << "scissors" << "scissors");
addIcon(0xf1c0, false, QStringList() << "database");
addIcon(0xf2a4, false, QStringList() << "deaf");
addIcon(0xf108, false, QStringList() << "desktop" << "monitor" << "screen" << "desktop" << "computer" << "demo" << "device");
addIcon(0xf155, false, QStringList() << "dollar sign" << "usd" << "usd");
addIcon(0xf192, false, QStringList() << "dot circle" << "target" << "bullseye" << "notification");
addIcon(0xf019, false, QStringList() << "download" << "import");
addIcon(0xf044, false, QStringList() << "edit" << "write" << "edit" << "update" << "pencil" << "pen");
addIcon(0xf052, false, QStringList() << "eject");
addIcon(0xf141, false, QStringList() << "horizontal ellipsis" << "dots");
addIcon(0xf142, false, QStringList() << "vertical ellipsis" << "dots");
addIcon(0xf0e0, false, QStringList() << "envelope" << "email" << "e-mail" << "letter" << "support" << "mail" << "message" << "notification");
addIcon(0xf2b6, false, QStringList() << "envelope open" << "email" << "e-mail" << "letter" << "support" << "mail" << "message" << "notification");
addIcon(0xf199, false, QStringList() << "envelope square" << "email" << "e-mail" << "letter" << "support" << "mail" << "message" << "notification");
addIcon(0xf12d, false, QStringList() << "eraser" << "remove" << "delete");
addIcon(0xf153, false, QStringList() << "euro sign" << "eur" << "eur");
addIcon(0xf362, false, QStringList() << "alternate exchange" << "transfer" << "arrows" << "arrow" << "exchange");
addIcon(0xf12a, false, QStringList() << "exclamation" << "warning" << "error" << "problem" << "notification" << "notify" << "alert");
addIcon(0xf06a, false, QStringList() << "exclamation circle" << "warning" << "error" << "problem" << "notification" << "notify" << "alert");
addIcon(0xf071, false, QStringList() << "exclamation triangle" << "warning" << "error" << "problem" << "notification" << "notify" << "alert");
addIcon(0xf065, false, QStringList() << "expand" << "enlarge" << "bigger" << "resize");
addIcon(0xf31e, false, QStringList() << "alternate expand arrows" << "enlarge" << "bigger" << "resize" << "move" << "arrows-alt");
addIcon(0xf35d, false, QStringList() << "alternate external link" << "open" << "new" << "external-link");
addIcon(0xf360, false, QStringList() << "alternate external link square" << "open" << "new" << "external-link-square");
addIcon(0xf06e, false, QStringList() << "eye" << "show" << "visible" << "views");
addIcon(0xf1fb, false, QStringList() << "eye dropper" << "eyedropper");
addIcon(0xf070, false, QStringList() << "eye slash" << "toggle" << "show" << "hide" << "visible" << "visiblity" << "views");
addIcon(0xf049, false, QStringList() << "fast-backward" << "rewind" << "previous" << "beginning" << "start" << "first");
addIcon(0xf050, false, QStringList() << "fast-forward" << "next" << "end" << "last");
addIcon(0xf1ac, false, QStringList() << "fax");
addIcon(0xf182, false, QStringList() << "female" << "woman" << "user" << "person" << "profile");
addIcon(0xf0fb, false, QStringList() << "fighter-jet" << "fly" << "plane" << "airplane" << "quick" << "fast" << "travel");
addIcon(0xf15b, false, QStringList() << "file" << "new" << "page" << "pdf" << "document");
addIcon(0xf15c, false, QStringList() << "alternate file" << "new" << "page" << "pdf" << "document" << "file-text");
addIcon(0xf1c6, false, QStringList() << "archive file");
addIcon(0xf1c7, false, QStringList() << "audio file");
addIcon(0xf1c9, false, QStringList() << "code file");
addIcon(0xf1c3, false, QStringList() << "excel file");
addIcon(0xf1c5, false, QStringList() << "image file");
addIcon(0xf1c1, false, QStringList() << "pdf file");
addIcon(0xf1c4, false, QStringList() << "powerpoint file");
addIcon(0xf1c8, false, QStringList() << "video file");
addIcon(0xf1c2, false, QStringList() << "word file");
addIcon(0xf008, false, QStringList() << "film" << "movie");
addIcon(0xf0b0, false, QStringList() << "filter" << "funnel" << "options");
addIcon(0xf06d, false, QStringList() << "fire" << "flame" << "hot" << "popular");
addIcon(0xf134, false, QStringList() << "fire-extinguisher");
addIcon(0xf024, false, QStringList() << "flag" << "report" << "notification" << "notify");
addIcon(0xf11e, false, QStringList() << "flag-checkered" << "report" << "notification" << "notify");
addIcon(0xf0c3, false, QStringList() << "flask" << "science" << "beaker" << "experimental" << "labs");
addIcon(0xf07b, false, QStringList() << "folder");
addIcon(0xf07c, false, QStringList() << "folder open");
addIcon(0xf031, false, QStringList() << "font" << "text");
addIcon(0xf04e, false, QStringList() << "forward" << "forward" << "next");
addIcon(0xf119, false, QStringList() << "frown" << "face" << "emoticon" << "sad" << "disapprove" << "rating");
addIcon(0xf1e3, false, QStringList() << "futbol");
addIcon(0xf11b, false, QStringList() << "gamepad" << "controller");
addIcon(0xf0e3, false, QStringList() << "gavel" << "judge" << "lawyer" << "opinion");
addIcon(0xf3a5, false, QStringList() << "gem" << "diamond");
addIcon(0xf22d, false, QStringList() << "genderless");
addIcon(0xf06b, false, QStringList() << "gift" << "present");
addIcon(0xf000, false, QStringList() << "martini glass" << "martini" << "drink" << "bar" << "alcohol" << "liquor" << "glass");
addIcon(0xf0ac, false, QStringList() << "globe" << "world" << "planet" << "map" << "place" << "travel" << "earth" << "global" << "translate" << "all" << "language" << "localize" << "location" << "coordinates" << "country");
addIcon(0xf19d, false, QStringList() << "graduation cap" << "learning" << "school" << "student");
addIcon(0xf0fd, false, QStringList() << "h square" << "hospital" << "hotel");
addIcon(0xf258, false, QStringList() << "lizard (hand)");
addIcon(0xf256, false, QStringList() << "paper (hand)" << "stop");
addIcon(0xf25b, false, QStringList() << "peace (hand)");
addIcon(0xf0a7, false, QStringList() << "hand pointing down" << "point" << "finger" << "hand-o-down");
addIcon(0xf0a5, false, QStringList() << "hand pointing left" << "point" << "left" << "previous" << "back" << "finger" << "hand-o-left");
addIcon(0xf0a4, false, QStringList() << "hand pointing right" << "point" << "right" << "next" << "forward" << "finger" << "hand-o-right");
addIcon(0xf0a6, false, QStringList() << "hand pointing up" << "point" << "finger" << "hand-o-up");
addIcon(0xf25a, false, QStringList() << "pointer (hand)");
addIcon(0xf255, false, QStringList() << "rock (hand)");
addIcon(0xf257, false, QStringList() << "scissors (hand)");
addIcon(0xf259, false, QStringList() << "spock (hand)");
addIcon(0xf2b5, false, QStringList() << "handshake");
addIcon(0xf292, false, QStringList() << "hashtag");
addIcon(0xf0a0, false, QStringList() << "hdd" << "harddrive" << "hard drive" << "storage" << "save");
addIcon(0xf1dc, false, QStringList() << "heading" << "header" << "header");
addIcon(0xf025, false, QStringList() << "headphones" << "sound" << "listen" << "music" << "audio");
addIcon(0xf004, false, QStringList() << "heart" << "love" << "like" << "favorite");
addIcon(0xf21e, false, QStringList() << "heartbeat" << "ekg");
addIcon(0xf1da, false, QStringList() << "history");
addIcon(0xf015, false, QStringList() << "home" << "main" << "house");
addIcon(0xf0f8, false, QStringList() << "hospital" << "building");
addIcon(0xf254, false, QStringList() << "hourglass");
addIcon(0xf253, false, QStringList() << "hourglass end");
addIcon(0xf252, false, QStringList() << "hourglass half");
addIcon(0xf251, false, QStringList() << "hourglass start");
addIcon(0xf246, false, QStringList() << "i beam cursor");
addIcon(0xf2c1, false, QStringList() << "identification badge");
addIcon(0xf2c2, false, QStringList() << "identification card");
addIcon(0xf03e, false, QStringList() << "image" << "photo" << "album" << "picture" << "picture");
addIcon(0xf302, false, QStringList() << "images" << "photo" << "album" << "picture");
addIcon(0xf01c, false, QStringList() << "inbox");
addIcon(0xf03c, false, QStringList() << "indent");
addIcon(0xf275, false, QStringList() << "industry" << "factory");
addIcon(0xf129, false, QStringList() << "info" << "help" << "information" << "more" << "details");
addIcon(0xf05a, false, QStringList() << "info circle" << "help" << "information" << "more" << "details");
addIcon(0xf033, false, QStringList() << "italic" << "italics");
addIcon(0xf084, false, QStringList() << "key" << "unlock" << "password");
addIcon(0xf11c, false, QStringList() << "keyboard" << "type" << "input");
addIcon(0xf1ab, false, QStringList() << "language");
addIcon(0xf109, false, QStringList() << "laptop" << "demo" << "computer" << "device");
addIcon(0xf06c, false, QStringList() << "leaf" << "eco" << "nature" << "plant");
addIcon(0xf094, false, QStringList() << "lemon" << "food");
addIcon(0xf3be, false, QStringList() << "level down-alt" << "level-down");
addIcon(0xf3bf, false, QStringList() << "level up-alt" << "level-up");
addIcon(0xf1cd, false, QStringList() << "life ring" << "support");
addIcon(0xf0eb, false, QStringList() << "lightbulb" << "idea" << "inspiration");
addIcon(0xf0c1, false, QStringList() << "link" << "chain");
addIcon(0xf195, false, QStringList() << "turkish lira sign" << "try" << "turkish" << "try");
addIcon(0xf03a, false, QStringList() << "list" << "ul" << "ol" << "checklist" << "finished" << "completed" << "done" << "todo");
addIcon(0xf022, false, QStringList() << "list-alt" << "ul" << "ol" << "checklist" << "finished" << "completed" << "done" << "todo");
addIcon(0xf0cb, false, QStringList() << "list-ol" << "ul" << "ol" << "checklist" << "list" << "todo" << "list" << "numbers");
addIcon(0xf0ca, false, QStringList() << "list-ul" << "ul" << "ol" << "checklist" << "todo" << "list");
addIcon(0xf124, false, QStringList() << "location-arrow" << "map" << "coordinates" << "location" << "address" << "place" << "where");
addIcon(0xf023, false, QStringList() << "lock" << "protect" << "admin" << "security");
addIcon(0xf3c1, false, QStringList() << "lock open" << "protect" << "admin" << "password" << "lock" << "open");
addIcon(0xf309, false, QStringList() << "alternate long arrow down" << "long-arrow-down");
addIcon(0xf30a, false, QStringList() << "alternate long arrow left" << "previous" << "back" << "long-arrow-left");
addIcon(0xf30b, false, QStringList() << "alternate long arrow right" << "long-arrow-right");
addIcon(0xf30c, false, QStringList() << "alternate long arrow up" << "long-arrow-up");
addIcon(0xf2a8, false, QStringList() << "low vision");
addIcon(0xf0d0, false, QStringList() << "magic" << "wizard" << "automatic" << "autocomplete");
addIcon(0xf076, false, QStringList() << "magnet");
addIcon(0xf183, false, QStringList() << "male" << "man" << "user" << "person" << "profile");
addIcon(0xf279, false, QStringList() << "map");
addIcon(0xf041, false, QStringList() << "map-marker" << "map" << "pin" << "location" << "coordinates" << "localize" << "address" << "travel" << "where" << "place");
addIcon(0xf3c5, false, QStringList() << "map marker-alt" << "map-marker");
addIcon(0xf276, false, QStringList() << "map pin");
addIcon(0xf277, false, QStringList() << "map signs");
addIcon(0xf222, false, QStringList() << "mars" << "male");
addIcon(0xf227, false, QStringList() << "mars double");
addIcon(0xf229, false, QStringList() << "mars stroke");
addIcon(0xf22b, false, QStringList() << "mars stroke horizontal");
addIcon(0xf22a, false, QStringList() << "mars stroke vertical");
addIcon(0xf0fa, false, QStringList() << "medkit" << "first aid" << "firstaid" << "help" << "support" << "health");
addIcon(0xf11a, false, QStringList() << "meh" << "face" << "emoticon" << "rating" << "neutral");
addIcon(0xf223, false, QStringList() << "mercury" << "transgender");
addIcon(0xf2db, false, QStringList() << "microchip");
addIcon(0xf130, false, QStringList() << "microphone" << "record" << "voice" << "sound");
addIcon(0xf131, false, QStringList() << "microphone slash" << "record" << "voice" << "sound" << "mute");
addIcon(0xf068, false, QStringList() << "minus" << "hide" << "minify" << "delete" << "remove" << "trash" << "hide" << "collapse");
addIcon(0xf056, false, QStringList() << "minus circle" << "delete" << "remove" << "trash" << "hide");
addIcon(0xf146, false, QStringList() << "minus square" << "hide" << "minify" << "delete" << "remove" << "trash" << "hide" << "collapse");
addIcon(0xf10b, false, QStringList() << "mobile phone" << "cell phone" << "cellphone" << "text" << "call" << "iphone" << "number" << "telephone");
addIcon(0xf3cd, false, QStringList() << "alternate mobile" << "mobile");
addIcon(0xf3d1, false, QStringList() << "money bill-alt" << "money");
addIcon(0xf186, false, QStringList() << "moon" << "night" << "darker" << "contrast");
addIcon(0xf21c, false, QStringList() << "motorcycle" << "vehicle" << "bike");
addIcon(0xf245, false, QStringList() << "mouse pointer");
addIcon(0xf001, false, QStringList() << "music" << "note" << "sound");
addIcon(0xf22c, false, QStringList() << "neuter");
addIcon(0xf1ea, false, QStringList() << "newspaper" << "press");
addIcon(0xf247, false, QStringList() << "object group");
addIcon(0xf248, false, QStringList() << "object ungroup");
addIcon(0xf03b, false, QStringList() << "outdent");
addIcon(0xf1fc, false, QStringList() << "paint brush");
addIcon(0xf1d8, false, QStringList() << "paper plane");
addIcon(0xf0c6, false, QStringList() << "paperclip" << "attachment");
addIcon(0xf1dd, false, QStringList() << "paragraph");
addIcon(0xf0ea, false, QStringList() << "paste" << "copy" << "clipboard");
addIcon(0xf04c, false, QStringList() << "pause" << "wait");
addIcon(0xf28b, false, QStringList() << "pause circle");
addIcon(0xf1b0, false, QStringList() << "paw" << "pet");
addIcon(0xf14b, false, QStringList() << "pen square" << "write" << "edit" << "update" << "pencil-square");
addIcon(0xf303, false, QStringList() << "alternate pencil" << "write" << "edit" << "update" << "pencil");
addIcon(0xf295, false, QStringList() << "percent");
addIcon(0xf095, false, QStringList() << "phone" << "call" << "voice" << "number" << "support" << "earphone" << "telephone");
addIcon(0xf098, false, QStringList() << "phone square" << "call" << "voice" << "number" << "support" << "telephone");
addIcon(0xf2a0, false, QStringList() << "phone volume" << "telephone" << "volume-control-phone");
addIcon(0xf072, false, QStringList() << "plane" << "travel" << "trip" << "location" << "destination" << "airplane" << "fly" << "mode");
addIcon(0xf04b, false, QStringList() << "play" << "start" << "playing" << "music" << "sound");
addIcon(0xf144, false, QStringList() << "play circle" << "start" << "playing");
addIcon(0xf1e6, false, QStringList() << "plug" << "power" << "connect");
addIcon(0xf067, false, QStringList() << "plus" << "add" << "new" << "create" << "expand");
addIcon(0xf055, false, QStringList() << "plus circle" << "add" << "new" << "create" << "expand");
addIcon(0xf0fe, false, QStringList() << "plus square" << "add" << "new" << "create" << "expand");
addIcon(0xf2ce, false, QStringList() << "podcast");
addIcon(0xf154, false, QStringList() << "pound sign" << "gbp" << "gbp");
addIcon(0xf011, false, QStringList() << "power off" << "on");
addIcon(0xf02f, false, QStringList() << "print");
addIcon(0xf12e, false, QStringList() << "puzzle piece" << "addon" << "add-on" << "section");
addIcon(0xf029, false, QStringList() << "qrcode" << "scan");
addIcon(0xf128, false, QStringList() << "question" << "help" << "information" << "unknown" << "support");
addIcon(0xf059, false, QStringList() << "question circle" << "help" << "information" << "unknown" << "support");
addIcon(0xf10d, false, QStringList() << "quote-left");
addIcon(0xf10e, false, QStringList() << "quote-right");
addIcon(0xf074, false, QStringList() << "random" << "sort" << "shuffle");
addIcon(0xf1b8, false, QStringList() << "recycle");
addIcon(0xf01e, false, QStringList() << "redo" << "forward" << "repeat" << "repeat");
addIcon(0xf2f9, false, QStringList() << "alternate redo" << "forward" << "repeat");
addIcon(0xf25d, false, QStringList() << "registered trademark");
addIcon(0xf3e5, false, QStringList() << "reply");
addIcon(0xf122, false, QStringList() << "reply-all");
addIcon(0xf079, false, QStringList() << "retweet" << "refresh" << "reload" << "share");
addIcon(0xf018, false, QStringList() << "road" << "street");
addIcon(0xf135, false, QStringList() << "rocket" << "app");
addIcon(0xf09e, false, QStringList() << "rss" << "blog");
addIcon(0xf143, false, QStringList() << "rss square" << "feed" << "blog");
addIcon(0xf158, false, QStringList() << "ruble sign" << "rub" << "rub");
addIcon(0xf156, false, QStringList() << "indian rupee sign" << "indian" << "inr");
addIcon(0xf0c7, false, QStringList() << "save" << "floppy" << "floppy-o");
addIcon(0xf002, false, QStringList() << "search" << "magnify" << "zoom" << "enlarge" << "bigger");
addIcon(0xf010, false, QStringList() << "search minus" << "magnify" << "minify" << "zoom" << "smaller");
addIcon(0xf00e, false, QStringList() << "search plus" << "magnify" << "zoom" << "enlarge" << "bigger");
addIcon(0xf233, false, QStringList() << "server");
addIcon(0xf064, false, QStringList() << "share");
addIcon(0xf1e0, false, QStringList() << "alternate share");
addIcon(0xf1e1, false, QStringList() << "alternate share square");
addIcon(0xf14d, false, QStringList() << "share square" << "social" << "send");
addIcon(0xf20b, false, QStringList() << "shekel sign" << "ils" << "ils");
addIcon(0xf3ed, false, QStringList() << "alternate shield" << "shield");
addIcon(0xf21a, false, QStringList() << "ship" << "boat" << "sea");
addIcon(0xf290, false, QStringList() << "shopping bag");
addIcon(0xf291, false, QStringList() << "shopping basket");
addIcon(0xf07a, false, QStringList() << "shopping-cart" << "checkout" << "buy" << "purchase" << "payment");
addIcon(0xf2cc, false, QStringList() << "shower");
addIcon(0xf2f6, false, QStringList() << "alernate sign in" << "enter" << "join" << "log in" << "login" << "sign up" << "sign in" << "signin" << "signup" << "arrow" << "sign-in");
addIcon(0xf2a7, false, QStringList() << "sign language");
addIcon(0xf2f5, false, QStringList() << "alernate sign out" << "log out" << "logout" << "leave" << "exit" << "arrow" << "sign-out");
addIcon(0xf012, false, QStringList() << "signal" << "graph" << "bars");
addIcon(0xf0e8, false, QStringList() << "sitemap" << "directory" << "hierarchy" << "organization");
addIcon(0xf1de, false, QStringList() << "horizontal sliders" << "settings" << "sliders");
addIcon(0xf118, false, QStringList() << "smile" << "face" << "emoticon" << "happy" << "approve" << "satisfied" << "rating");
addIcon(0xf2dc, false, QStringList() << "snowflake");
addIcon(0xf0dc, false, QStringList() << "sort" << "order");
addIcon(0xf15d, false, QStringList() << "sort alpha down" << "sort-alpha-asc");
addIcon(0xf15e, false, QStringList() << "sort alpha up" << "sort-alpha-desc");
addIcon(0xf160, false, QStringList() << "sort amount down" << "sort-amount-asc");
addIcon(0xf161, false, QStringList() << "sort amount up" << "sort-amount-desc");
addIcon(0xf0dd, false, QStringList() << "sort down (descending)" << "arrow" << "descending" << "sort-desc");
addIcon(0xf162, false, QStringList() << "sort numeric down" << "numbers" << "sort-numeric-asc");
addIcon(0xf163, false, QStringList() << "sort numeric up" << "numbers" << "sort-numeric-desc");
addIcon(0xf0de, false, QStringList() << "sort up (ascending)" << "arrow" << "ascending" << "sort-asc");
addIcon(0xf197, false, QStringList() << "space shuttle");
addIcon(0xf110, false, QStringList() << "spinner" << "loading" << "progress");
addIcon(0xf0c8, false, QStringList() << "square" << "block" << "box");
addIcon(0xf005, false, QStringList() << "star" << "award" << "achievement" << "night" << "rating" << "score" << "favorite");
addIcon(0xf089, false, QStringList() << "star-half" << "award" << "achievement" << "rating" << "score" << "star-half-empty" << "star-half-full");
addIcon(0xf048, false, QStringList() << "step-backward" << "rewind" << "previous" << "beginning" << "start" << "first");
addIcon(0xf051, false, QStringList() << "step-forward" << "next" << "end" << "last");
addIcon(0xf0f1, false, QStringList() << "stethoscope");
addIcon(0xf249, false, QStringList() << "sticky note");
addIcon(0xf04d, false, QStringList() << "stop" << "block" << "box" << "square");
addIcon(0xf28d, false, QStringList() << "stop circle");
addIcon(0xf2f2, false, QStringList() << "stopwatch" << "time");
addIcon(0xf21d, false, QStringList() << "street view" << "map");
addIcon(0xf0cc, false, QStringList() << "strikethrough");
addIcon(0xf12c, false, QStringList() << "subscript");
addIcon(0xf239, false, QStringList() << "subway");
addIcon(0xf0f2, false, QStringList() << "suitcase" << "trip" << "luggage" << "travel" << "move" << "baggage");
addIcon(0xf185, false, QStringList() << "sun" << "weather" << "contrast" << "lighter" << "brighten" << "day");
addIcon(0xf12b, false, QStringList() << "superscript" << "exponential");
addIcon(0xf021, false, QStringList() << "sync" << "reload" << "refresh" << "refresh");
addIcon(0xf2f1, false, QStringList() << "alternate sync" << "reload" << "refresh");
addIcon(0xf0ce, false, QStringList() << "table" << "data" << "excel" << "spreadsheet");
addIcon(0xf10a, false, QStringList() << "tablet" << "ipad" << "device");
addIcon(0xf3fa, false, QStringList() << "alternate tablet" << "tablet");
addIcon(0xf3fd, false, QStringList() << "alternate tachometer" << "tachometer");
addIcon(0xf02b, false, QStringList() << "tag" << "label");
addIcon(0xf02c, false, QStringList() << "tags" << "labels");
addIcon(0xf0ae, false, QStringList() << "tasks" << "progress" << "loading" << "downloading" << "downloads" << "settings");
addIcon(0xf1ba, false, QStringList() << "taxi" << "vehicle");
addIcon(0xf120, false, QStringList() << "terminal" << "command" << "prompt" << "code");
addIcon(0xf034, false, QStringList() << "text-height");
addIcon(0xf035, false, QStringList() << "text-width");
addIcon(0xf00a, false, QStringList() << "th" << "blocks" << "squares" << "boxes" << "grid");
addIcon(0xf009, false, QStringList() << "th-large" << "blocks" << "squares" << "boxes" << "grid");
addIcon(0xf00b, false, QStringList() << "th-list" << "ul" << "ol" << "checklist" << "finished" << "completed" << "done" << "todo");
addIcon(0xf2cb, false, QStringList() << "thermometer empty");
addIcon(0xf2c7, false, QStringList() << "thermometer full");
addIcon(0xf2c9, false, QStringList() << "thermometer 1/2 full");
addIcon(0xf2ca, false, QStringList() << "thermometer 1/4 full");
addIcon(0xf2c8, false, QStringList() << "thermometer 3/4 full");
addIcon(0xf165, false, QStringList() << "thumbs-down" << "dislike" << "disapprove" << "disagree" << "hand" << "thumbs-o-down");
addIcon(0xf164, false, QStringList() << "thumbs-up" << "like" << "favorite" << "approve" << "agree" << "hand" << "thumbs-o-up");
addIcon(0xf08d, false, QStringList() << "thumbtack" << "marker" << "pin" << "location" << "coordinates" << "thumb-tack");
addIcon(0xf3ff, false, QStringList() << "alernate ticket" << "ticket");
addIcon(0xf00d, false, QStringList() << "times" << "close" << "exit" << "x" << "cross");
addIcon(0xf057, false, QStringList() << "times circle" << "close" << "exit" << "x");
addIcon(0xf043, false, QStringList() << "tint" << "raindrop" << "waterdrop" << "drop" << "droplet");
addIcon(0xf204, false, QStringList() << "toggle off");
addIcon(0xf205, false, QStringList() << "toggle on");
addIcon(0xf25c, false, QStringList() << "trademark");
addIcon(0xf238, false, QStringList() << "train");
addIcon(0xf224, false, QStringList() << "transgender" << "intersex");
addIcon(0xf225, false, QStringList() << "alternate transgender");
addIcon(0xf1f8, false, QStringList() << "trash" << "garbage" << "delete" << "remove" << "hide");
addIcon(0xf2ed, false, QStringList() << "alternate trash" << "garbage" << "delete" << "remove" << "hide" << "trash" << "trash-o");
addIcon(0xf1bb, false, QStringList() << "tree");
addIcon(0xf091, false, QStringList() << "trophy" << "award" << "achievement" << "cup" << "winner" << "game");
addIcon(0xf0d1, false, QStringList() << "truck" << "shipping");
addIcon(0xf1e4, false, QStringList() << "tty");
addIcon(0xf26c, false, QStringList() << "television" << "display" << "computer" << "monitor" << "television");
addIcon(0xf0e9, false, QStringList() << "umbrella");
addIcon(0xf0cd, false, QStringList() << "underline");
addIcon(0xf0e2, false, QStringList() << "undo" << "back");
addIcon(0xf2ea, false, QStringList() << "alternate undo" << "back");
addIcon(0xf29a, false, QStringList() << "universal access");
addIcon(0xf19c, false, QStringList() << "university");
addIcon(0xf127, false, QStringList() << "unlink" << "remove" << "chain" << "chain-broken");
addIcon(0xf09c, false, QStringList() << "unlock" << "protect" << "admin" << "password" << "lock");
addIcon(0xf13e, false, QStringList() << "alternate unlock" << "protect" << "admin" << "password" << "lock");
addIcon(0xf093, false, QStringList() << "upload" << "import");
addIcon(0xf007, false, QStringList() << "user" << "person" << "man" << "head" << "profile");
addIcon(0xf2bd, false, QStringList() << "user circle");
addIcon(0xf0f0, false, QStringList() << "user-md" << "doctor" << "profile" << "medical" << "nurse");
addIcon(0xf234, false, QStringList() << "add user" << "sign up" << "signup");
addIcon(0xf21b, false, QStringList() << "user secret" << "whisper" << "spy" << "incognito" << "privacy");
addIcon(0xf235, false, QStringList() << "remove user");
addIcon(0xf0c0, false, QStringList() << "users" << "people" << "profiles" << "persons");
addIcon(0xf2e5, false, QStringList() << "utensil spoon" << "spoon");
addIcon(0xf2e7, false, QStringList() << "utensils" << "food" << "restaurant" << "spoon" << "knife" << "dinner" << "eat" << "cutlery");
addIcon(0xf221, false, QStringList() << "venus" << "female");
addIcon(0xf226, false, QStringList() << "venus double");
addIcon(0xf228, false, QStringList() << "venus mars");
addIcon(0xf03d, false, QStringList() << "video" << "film" << "movie" << "record" << "camera" << "video-camera");
addIcon(0xf027, false, QStringList() << "volume-down" << "audio" << "lower" << "quieter" << "sound" << "music");
addIcon(0xf026, false, QStringList() << "volume-off" << "audio" << "mute" << "sound" << "music");
addIcon(0xf028, false, QStringList() << "volume-up" << "audio" << "higher" << "louder" << "sound" << "music");
addIcon(0xf193, false, QStringList() << "wheelchair" << "handicap" << "person");
addIcon(0xf1eb, false, QStringList() << "wifi");
addIcon(0xf410, false, QStringList() << "window close");
addIcon(0xf2d0, false, QStringList() << "window maximize");
addIcon(0xf2d1, false, QStringList() << "window minimize");
addIcon(0xf2d2, false, QStringList() << "window restore");
addIcon(0xf159, false, QStringList() << "won sign" << "krw" << "krw");
addIcon(0xf0ad, false, QStringList() << "wrench" << "settings" << "fix" << "update" << "spanner");
addIcon(0xf157, false, QStringList() << "yen sign" << "jpy" << "jpy");
addIcon(0xf26e, true, QStringList() << "500px");
addIcon(0xf368, true, QStringList() << "accessible icon" << "accessibility" << "wheelchair" << "handicap" << "person" << "wheelchair-alt");
addIcon(0xf369, true, QStringList() << "accusoft");
addIcon(0xf170, true, QStringList() << "app.net");
addIcon(0xf36a, true, QStringList() << "adversal");
addIcon(0xf36b, true, QStringList() << "affiliatetheme");
addIcon(0xf36c, true, QStringList() << "algolia");
addIcon(0xf270, true, QStringList() << "amazon");
addIcon(0xf42c, true, QStringList() << "amazon pay");
addIcon(0xf36d, true, QStringList() << "amilia");
addIcon(0xf17b, true, QStringList() << "android" << "robot");
addIcon(0xf209, true, QStringList() << "angellist");
addIcon(0xf36e, true, QStringList() << "angry creative");
addIcon(0xf420, true, QStringList() << "angular");
addIcon(0xf36f, true, QStringList() << "app store");
addIcon(0xf370, true, QStringList() << "ios app store");
addIcon(0xf371, true, QStringList() << "apper systems ab");
addIcon(0xf179, true, QStringList() << "apple" << "osx" << "food");
addIcon(0xf415, true, QStringList() << "apple pay");
addIcon(0xf372, true, QStringList() << "asymmetrik, ltd.");
addIcon(0xf373, true, QStringList() << "audible");
addIcon(0xf41c, true, QStringList() << "autoprefixer");
addIcon(0xf374, true, QStringList() << "avianex");
addIcon(0xf421, true, QStringList() << "aviato");
addIcon(0xf375, true, QStringList() << "amazon web services (aws)");
addIcon(0xf2d5, true, QStringList() << "bandcamp");
addIcon(0xf1b4, true, QStringList() << "behance");
addIcon(0xf1b5, true, QStringList() << "behance square");
addIcon(0xf378, true, QStringList() << "bimobject");
addIcon(0xf171, true, QStringList() << "bitbucket" << "git" << "bitbucket-square");
addIcon(0xf379, true, QStringList() << "bitcoin");
addIcon(0xf37a, true, QStringList() << "bity");
addIcon(0xf27e, true, QStringList() << "font awesome black tie");
addIcon(0xf37b, true, QStringList() << "blackberry");
addIcon(0xf37c, true, QStringList() << "blogger");
addIcon(0xf37d, true, QStringList() << "blogger b");
addIcon(0xf293, true, QStringList() << "bluetooth");
addIcon(0xf294, true, QStringList() << "bluetooth");
addIcon(0xf15a, true, QStringList() << "btc");
addIcon(0xf37f, true, QStringList() << "b\u00fcrom\u00f6bel-experte gmbh & co. kg.");
addIcon(0xf20d, true, QStringList() << "buysellads");
addIcon(0xf42d, true, QStringList() << "amazon pay credit card");
addIcon(0xf1f3, true, QStringList() << "american express credit card" << "amex");
addIcon(0xf416, true, QStringList() << "apple pay credit card");
addIcon(0xf24c, true, QStringList() << "diner's club credit card");
addIcon(0xf1f2, true, QStringList() << "discover credit card");
addIcon(0xf24b, true, QStringList() << "jcb credit card");
addIcon(0xf1f1, true, QStringList() << "mastercard credit card");
addIcon(0xf1f4, true, QStringList() << "paypal credit card");
addIcon(0xf1f5, true, QStringList() << "stripe credit card");
addIcon(0xf1f0, true, QStringList() << "visa credit card");
addIcon(0xf380, true, QStringList() << "centercode");
addIcon(0xf268, true, QStringList() << "chrome" << "browser");
addIcon(0xf383, true, QStringList() << "cloudscale.ch");
addIcon(0xf384, true, QStringList() << "cloudsmith");
addIcon(0xf385, true, QStringList() << "cloudversify");
addIcon(0xf1cb, true, QStringList() << "codepen");
addIcon(0xf284, true, QStringList() << "codie pie");
addIcon(0xf20e, true, QStringList() << "connect develop");
addIcon(0xf26d, true, QStringList() << "contao");
addIcon(0xf388, true, QStringList() << "cpanel");
addIcon(0xf25e, true, QStringList() << "creative commons");
addIcon(0xf13c, true, QStringList() << "css 3 logo" << "code");
addIcon(0xf38b, true, QStringList() << "alternate css3 logo");
addIcon(0xf38c, true, QStringList() << "cuttlefish");
addIcon(0xf38d, true, QStringList() << "dungeons & dragons");
addIcon(0xf210, true, QStringList() << "dashcube");
addIcon(0xf1a5, true, QStringList() << "delicious logo");
addIcon(0xf38e, true, QStringList() << "deploy.dog");
addIcon(0xf38f, true, QStringList() << "deskpro");
addIcon(0xf1bd, true, QStringList() << "deviantart");
addIcon(0xf1a6, true, QStringList() << "digg logo");
addIcon(0xf391, true, QStringList() << "digital ocean");
addIcon(0xf392, true, QStringList() << "discord");
addIcon(0xf393, true, QStringList() << "discourse");
addIcon(0xf394, true, QStringList() << "dochub");
addIcon(0xf395, true, QStringList() << "docker");
addIcon(0xf396, true, QStringList() << "draft2digital");
addIcon(0xf17d, true, QStringList() << "dribbble");
addIcon(0xf397, true, QStringList() << "dribbble square");
addIcon(0xf16b, true, QStringList() << "dropbox");
addIcon(0xf1a9, true, QStringList() << "drupal logo");
addIcon(0xf399, true, QStringList() << "dyalog");
addIcon(0xf39a, true, QStringList() << "earlybirds");
addIcon(0xf282, true, QStringList() << "edge browser" << "browser" << "ie");
addIcon(0xf423, true, QStringList() << "ember");
addIcon(0xf1d1, true, QStringList() << "galactic empire");
addIcon(0xf299, true, QStringList() << "envira gallery" << "leaf");
addIcon(0xf39d, true, QStringList() << "erlang");
addIcon(0xf42e, true, QStringList() << "ethereum");
addIcon(0xf2d7, true, QStringList() << "etsy");
addIcon(0xf23e, true, QStringList() << "expeditedssl");
addIcon(0xf09a, true, QStringList() << "facebook" << "social network" << "facebook-official");
addIcon(0xf39e, true, QStringList() << "facebook f" << "facebook");
addIcon(0xf39f, true, QStringList() << "facebook messenger");
addIcon(0xf082, true, QStringList() << "facebook square" << "social network");
addIcon(0xf269, true, QStringList() << "firefox" << "browser");
addIcon(0xf2b0, true, QStringList() << "first order");
addIcon(0xf3a1, true, QStringList() << "firstdraft");
addIcon(0xf16e, true, QStringList() << "flickr");
addIcon(0xf417, true, QStringList() << "fly");
addIcon(0xf2b4, true, QStringList() << "font awesome" << "meanpath");
addIcon(0xf35c, true, QStringList() << "alternate font awesome");
addIcon(0xf425, true, QStringList() << "font awesome flag");
addIcon(0xf280, true, QStringList() << "fonticons");
addIcon(0xf3a2, true, QStringList() << "fonticons fi");
addIcon(0xf286, true, QStringList() << "fort awesome");
addIcon(0xf3a3, true, QStringList() << "alternate fort awesome");
addIcon(0xf211, true, QStringList() << "forumbee");
addIcon(0xf180, true, QStringList() << "foursquare");
addIcon(0xf2c5, true, QStringList() << "free code camp");
addIcon(0xf3a4, true, QStringList() << "freebsd");
addIcon(0xf265, true, QStringList() << "get pocket");
addIcon(0xf260, true, QStringList() << "gg currency");
addIcon(0xf261, true, QStringList() << "gg currency circle");
addIcon(0xf1d3, true, QStringList() << "git");
addIcon(0xf1d2, true, QStringList() << "git square");
addIcon(0xf09b, true, QStringList() << "github" << "octocat");
addIcon(0xf113, true, QStringList() << "alternate github" << "octocat");
addIcon(0xf092, true, QStringList() << "github square" << "octocat");
addIcon(0xf3a6, true, QStringList() << "gitkraken");
addIcon(0xf296, true, QStringList() << "gitlab" << "Axosoft");
addIcon(0xf426, true, QStringList() << "gitter");
addIcon(0xf2a5, true, QStringList() << "glide");
addIcon(0xf2a6, true, QStringList() << "glide g");
addIcon(0xf3a7, true, QStringList() << "gofore");
addIcon(0xf3a8, true, QStringList() << "goodreads");
addIcon(0xf3a9, true, QStringList() << "goodreads g");
addIcon(0xf1a0, true, QStringList() << "google logo");
addIcon(0xf3aa, true, QStringList() << "google drive");
addIcon(0xf3ab, true, QStringList() << "google play");
addIcon(0xf2b3, true, QStringList() << "google plus" << "google-plus-circle" << "google-plus-official");
addIcon(0xf0d5, true, QStringList() << "google plus g" << "social network" << "google-plus");
addIcon(0xf0d4, true, QStringList() << "google plus square" << "social network");
addIcon(0xf1ee, true, QStringList() << "google wallet");
addIcon(0xf184, true, QStringList() << "gratipay (gittip)" << "heart" << "like" << "favorite" << "love");
addIcon(0xf2d6, true, QStringList() << "grav");
addIcon(0xf3ac, true, QStringList() << "gripfire, inc.");
addIcon(0xf3ad, true, QStringList() << "grunt");
addIcon(0xf3ae, true, QStringList() << "gulp");
addIcon(0xf1d4, true, QStringList() << "hacker news");
addIcon(0xf3af, true, QStringList() << "hacker news square");
addIcon(0xf3b0, true, QStringList() << "hireahelper");
addIcon(0xf427, true, QStringList() << "hooli");
addIcon(0xf3b1, true, QStringList() << "hotjar");
addIcon(0xf27c, true, QStringList() << "houzz");
addIcon(0xf13b, true, QStringList() << "html 5 logo");
addIcon(0xf3b2, true, QStringList() << "hubspot");
addIcon(0xf2d8, true, QStringList() << "imdb");
addIcon(0xf16d, true, QStringList() << "instagram");
addIcon(0xf26b, true, QStringList() << "internet-explorer" << "browser" << "ie");
addIcon(0xf208, true, QStringList() << "ioxhost");
addIcon(0xf3b4, true, QStringList() << "itunes");
addIcon(0xf3b5, true, QStringList() << "itunes note");
addIcon(0xf3b6, true, QStringList() << "jenkis");
addIcon(0xf3b7, true, QStringList() << "joget");
addIcon(0xf1aa, true, QStringList() << "joomla logo");
addIcon(0xf3b8, true, QStringList() << "javascript (js)");
addIcon(0xf3b9, true, QStringList() << "javascript (js) square");
addIcon(0xf1cc, true, QStringList() << "jsfiddle");
addIcon(0xf3ba, true, QStringList() << "keycdn");
addIcon(0xf3bb, true, QStringList() << "kickstarter");
addIcon(0xf3bc, true, QStringList() << "kickstarter k");
addIcon(0xf42f, true, QStringList() << "korvue");
addIcon(0xf3bd, true, QStringList() << "laravel");
addIcon(0xf202, true, QStringList() << "last.fm");
addIcon(0xf203, true, QStringList() << "last.fm square");
addIcon(0xf212, true, QStringList() << "leanpub");
addIcon(0xf41d, true, QStringList() << "less");
addIcon(0xf3c0, true, QStringList() << "line");
addIcon(0xf08c, true, QStringList() << "linkedin" << "linkedin-square");
addIcon(0xf0e1, true, QStringList() << "linkedin in" << "linkedin");
addIcon(0xf2b8, true, QStringList() << "linode");
addIcon(0xf17c, true, QStringList() << "linux" << "tux");
addIcon(0xf3c3, true, QStringList() << "lyft");
addIcon(0xf3c4, true, QStringList() << "magento");
addIcon(0xf136, true, QStringList() << "maxcdn");
addIcon(0xf3c6, true, QStringList() << "medapps");
addIcon(0xf23a, true, QStringList() << "medium");
addIcon(0xf3c7, true, QStringList() << "medium m");
addIcon(0xf3c8, true, QStringList() << "mrt");
addIcon(0xf2e0, true, QStringList() << "meetup");
addIcon(0xf3ca, true, QStringList() << "microsoft");
addIcon(0xf3cb, true, QStringList() << "mix");
addIcon(0xf289, true, QStringList() << "mixcloud");
addIcon(0xf3cc, true, QStringList() << "mizuni");
addIcon(0xf285, true, QStringList() << "modx");
addIcon(0xf3d0, true, QStringList() << "monero");
addIcon(0xf3d2, true, QStringList() << "napster");
addIcon(0xf418, true, QStringList() << "nintendo switch");
addIcon(0xf419, true, QStringList() << "node.js");
addIcon(0xf3d3, true, QStringList() << "node.js js");
addIcon(0xf3d4, true, QStringList() << "npm");
addIcon(0xf3d5, true, QStringList() << "ns8");
addIcon(0xf3d6, true, QStringList() << "nutritionix");
addIcon(0xf263, true, QStringList() << "odnoklassniki");
addIcon(0xf264, true, QStringList() << "odnoklassniki square");
addIcon(0xf23d, true, QStringList() << "opencart");
addIcon(0xf19b, true, QStringList() << "openid");
addIcon(0xf26a, true, QStringList() << "opera");
addIcon(0xf23c, true, QStringList() << "optin monster");
addIcon(0xf41a, true, QStringList() << "open source initiative");
addIcon(0xf3d7, true, QStringList() << "page4 corporation");
addIcon(0xf18c, true, QStringList() << "pagelines" << "leaf" << "leaves" << "tree" << "plant" << "eco" << "nature");
addIcon(0xf3d8, true, QStringList() << "palfed");
addIcon(0xf3d9, true, QStringList() << "patreon");
addIcon(0xf1ed, true, QStringList() << "paypal");
addIcon(0xf3da, true, QStringList() << "periscope");
addIcon(0xf3db, true, QStringList() << "phabricator");
addIcon(0xf3dc, true, QStringList() << "phoenix framework");
addIcon(0xf2ae, true, QStringList() << "pied piper logo");
addIcon(0xf1a8, true, QStringList() << "alternate pied piper logo");
addIcon(0xf1a7, true, QStringList() << "pied piper pp logo (old)");
addIcon(0xf0d2, true, QStringList() << "pinterest");
addIcon(0xf231, true, QStringList() << "pinterest p");
addIcon(0xf0d3, true, QStringList() << "pinterest square");
addIcon(0xf3df, true, QStringList() << "playstation");
addIcon(0xf288, true, QStringList() << "product hunt");
addIcon(0xf3e1, true, QStringList() << "pushed");
addIcon(0xf3e2, true, QStringList() << "python");
addIcon(0xf1d6, true, QStringList() << "qq");
addIcon(0xf2c4, true, QStringList() << "quora");
addIcon(0xf2d9, true, QStringList() << "ravelry");
addIcon(0xf41b, true, QStringList() << "react");
addIcon(0xf1d0, true, QStringList() << "rebel alliance");
addIcon(0xf3e3, true, QStringList() << "red river");
addIcon(0xf1a1, true, QStringList() << "reddit logo");
addIcon(0xf281, true, QStringList() << "reddit alien");
addIcon(0xf1a2, true, QStringList() << "reddit square");
addIcon(0xf3e4, true, QStringList() << "rendact");
addIcon(0xf18b, true, QStringList() << "renren");
addIcon(0xf3e6, true, QStringList() << "replyd");
addIcon(0xf3e7, true, QStringList() << "resolving");
addIcon(0xf3e8, true, QStringList() << "rocket.chat");
addIcon(0xf3e9, true, QStringList() << "rockrms");
addIcon(0xf267, true, QStringList() << "safari" << "browser");
addIcon(0xf41e, true, QStringList() << "sass");
addIcon(0xf3ea, true, QStringList() << "schlix");
addIcon(0xf28a, true, QStringList() << "scribd");
addIcon(0xf3eb, true, QStringList() << "searchengin");
addIcon(0xf2da, true, QStringList() << "sellcast" << "eercast");
addIcon(0xf213, true, QStringList() << "sellsy");
addIcon(0xf3ec, true, QStringList() << "servicestack");
addIcon(0xf214, true, QStringList() << "shirts in bulk");
addIcon(0xf215, true, QStringList() << "simplybuilt");
addIcon(0xf3ee, true, QStringList() << "sistrix");
addIcon(0xf216, true, QStringList() << "skyatlas");
addIcon(0xf17e, true, QStringList() << "skype");
addIcon(0xf198, true, QStringList() << "slack logo" << "hashtag" << "anchor" << "hash");
addIcon(0xf3ef, true, QStringList() << "slack hashtag" << "hashtag" << "anchor" << "hash");
addIcon(0xf1e7, true, QStringList() << "slideshare");
addIcon(0xf2ab, true, QStringList() << "snapchat");
addIcon(0xf2ac, true, QStringList() << "snapchat ghost");
addIcon(0xf2ad, true, QStringList() << "snapchat square");
addIcon(0xf1be, true, QStringList() << "soundcloud");
addIcon(0xf3f3, true, QStringList() << "speakap");
addIcon(0xf1bc, true, QStringList() << "spotify");
addIcon(0xf18d, true, QStringList() << "stack exchange");
addIcon(0xf16c, true, QStringList() << "stack overflow");
addIcon(0xf3f5, true, QStringList() << "staylinked");
addIcon(0xf1b6, true, QStringList() << "steam");
addIcon(0xf1b7, true, QStringList() << "steam square");
addIcon(0xf3f6, true, QStringList() << "steam symbol");
addIcon(0xf3f7, true, QStringList() << "sticker mule");
addIcon(0xf428, true, QStringList() << "strava");
addIcon(0xf429, true, QStringList() << "stripe");
addIcon(0xf42a, true, QStringList() << "stripe s");
addIcon(0xf3f8, true, QStringList() << "studio vinari");
addIcon(0xf1a4, true, QStringList() << "stumbleupon logo");
addIcon(0xf1a3, true, QStringList() << "stumbleupon circle");
addIcon(0xf2dd, true, QStringList() << "superpowers");
addIcon(0xf3f9, true, QStringList() << "supple");
addIcon(0xf2c6, true, QStringList() << "telegram");
addIcon(0xf3fe, true, QStringList() << "telegram plane");
addIcon(0xf1d5, true, QStringList() << "tencent weibo");
addIcon(0xf2b2, true, QStringList() << "themeisle");
addIcon(0xf181, true, QStringList() << "trello");
addIcon(0xf262, true, QStringList() << "tripadvisor");
addIcon(0xf173, true, QStringList() << "tumblr");
addIcon(0xf174, true, QStringList() << "tumblr square");
addIcon(0xf1e8, true, QStringList() << "twitch");
addIcon(0xf099, true, QStringList() << "twitter" << "tweet" << "social network");
addIcon(0xf081, true, QStringList() << "twitter square" << "tweet" << "social network");
addIcon(0xf42b, true, QStringList() << "typo3");
addIcon(0xf402, true, QStringList() << "uber");
addIcon(0xf403, true, QStringList() << "uikit");
addIcon(0xf404, true, QStringList() << "uniregistry");
addIcon(0xf405, true, QStringList() << "untappd");
addIcon(0xf287, true, QStringList() << "usb");
addIcon(0xf407, true, QStringList() << "us-sunnah foundation");
addIcon(0xf408, true, QStringList() << "vaadin");
addIcon(0xf237, true, QStringList() << "viacoin");
addIcon(0xf2a9, true, QStringList() << "viadeo");
addIcon(0xf2aa, true, QStringList() << "viadeo square");
addIcon(0xf409, true, QStringList() << "viber");
addIcon(0xf40a, true, QStringList() << "vimeo");
addIcon(0xf194, true, QStringList() << "vimeo square");
addIcon(0xf27d, true, QStringList() << "vimeo" << "vimeo");
addIcon(0xf1ca, true, QStringList() << "vine");
addIcon(0xf189, true, QStringList() << "vk");
addIcon(0xf40b, true, QStringList() << "vnv");
addIcon(0xf41f, true, QStringList() << "vue.js");
addIcon(0xf18a, true, QStringList() << "weibo");
addIcon(0xf1d7, true, QStringList() << "weixin (wechat)");
addIcon(0xf232, true, QStringList() << "what's app");
addIcon(0xf40c, true, QStringList() << "what's app square");
addIcon(0xf40d, true, QStringList() << "whmcs");
addIcon(0xf266, true, QStringList() << "wikipedia w");
addIcon(0xf17a, true, QStringList() << "windows" << "microsoft");
addIcon(0xf19a, true, QStringList() << "wordpress logo");
addIcon(0xf411, true, QStringList() << "wordpress simple");
addIcon(0xf297, true, QStringList() << "wpbeginner");
addIcon(0xf2de, true, QStringList() << "wpexplorer");
addIcon(0xf298, true, QStringList() << "wpforms");
addIcon(0xf412, true, QStringList() << "xbox");
addIcon(0xf168, true, QStringList() << "xing");
addIcon(0xf169, true, QStringList() << "xing square");
addIcon(0xf23b, true, QStringList() << "y combinator");
addIcon(0xf19e, true, QStringList() << "yahoo logo");
addIcon(0xf413, true, QStringList() << "yandex");
addIcon(0xf414, true, QStringList() << "yandex international");
addIcon(0xf1e9, true, QStringList() << "yelp");
addIcon(0xf2b1, true, QStringList() << "yoast");
addIcon(0xf167, true, QStringList() << "youtube" << "video" << "film" << "youtube-play" << "youtube-square");
