// This file is generated with "update_icon_font.py" from FontAwesome's metadata.

// List of method calls for IconSelectDialog.
addIcon(0xf2b9, false, QStringList() << "address book");
addIcon(0xf2bb, false, QStringList() << "address card");
addIcon(0xf042, false, QStringList() << "adjust" << "contrast");
addIcon(0xf5d0, false, QStringList() << "air freshener");
addIcon(0xf037, false, QStringList() << "align-center" << "middle" << "text");
addIcon(0xf039, false, QStringList() << "align-justify" << "text");
addIcon(0xf036, false, QStringList() << "align-left" << "text");
addIcon(0xf038, false, QStringList() << "align-right" << "text");
addIcon(0xf461, false, QStringList() << "allergies" << "freckles" << "hand" << "intolerances" << "pox" << "spots");
addIcon(0xf0f9, false, QStringList() << "ambulance" << "help" << "machine" << "support" << "vehicle");
addIcon(0xf2a3, false, QStringList() << "american sign language interpreting");
addIcon(0xf13d, false, QStringList() << "anchor" << "link");
addIcon(0xf103, false, QStringList() << "angle double down" << "arrows");
addIcon(0xf100, false, QStringList() << "angle double left" << "arrows" << "back" << "laquo" << "previous" << "quote");
addIcon(0xf101, false, QStringList() << "angle double right" << "arrows" << "forward" << "next" << "quote" << "raquo");
addIcon(0xf102, false, QStringList() << "angle double up" << "arrows");
addIcon(0xf107, false, QStringList() << "angle-down" << "arrow");
addIcon(0xf104, false, QStringList() << "angle-left" << "arrow" << "back" << "previous");
addIcon(0xf105, false, QStringList() << "angle-right" << "arrow" << "forward" << "next");
addIcon(0xf106, false, QStringList() << "angle-up" << "arrow");
addIcon(0xf556, false, QStringList() << "angry face" << "disapprove" << "emoticon" << "face" << "mad" << "upset");
addIcon(0xf5d1, false, QStringList() << "fruit apple");
addIcon(0xf187, false, QStringList() << "archive" << "box" << "package" << "storage");
addIcon(0xf557, false, QStringList() << "archway" << "arc" << "monument" << "road" << "street");
addIcon(0xf358, false, QStringList() << "alternate arrow circle down" << "arrow-circle-o-down" << "download");
addIcon(0xf359, false, QStringList() << "alternate arrow circle left" << "arrow-circle-o-left" << "back" << "previous");
addIcon(0xf35a, false, QStringList() << "alternate arrow circle right" << "arrow-circle-o-right" << "forward" << "next");
addIcon(0xf35b, false, QStringList() << "alternate arrow circle up" << "arrow-circle-o-up");
addIcon(0xf0ab, false, QStringList() << "arrow circle down" << "download");
addIcon(0xf0a8, false, QStringList() << "arrow circle left" << "back" << "previous");
addIcon(0xf0a9, false, QStringList() << "arrow circle right" << "forward" << "next");
addIcon(0xf0aa, false, QStringList() << "arrow circle up");
addIcon(0xf063, false, QStringList() << "arrow-down" << "download");
addIcon(0xf060, false, QStringList() << "arrow-left" << "back" << "previous");
addIcon(0xf061, false, QStringList() << "arrow-right" << "forward" << "next");
addIcon(0xf062, false, QStringList() << "arrow-up");
addIcon(0xf0b2, false, QStringList() << "alternate arrows" << "arrow" << "arrows" << "bigger" << "enlarge" << "expand" << "fullscreen" << "move" << "position" << "reorder" << "resize");
addIcon(0xf337, false, QStringList() << "alternate arrows horizontal" << "arrows-h" << "resize");
addIcon(0xf338, false, QStringList() << "alternate arrows vertical" << "arrows-v" << "resize");
addIcon(0xf2a2, false, QStringList() << "assistive listening systems");
addIcon(0xf069, false, QStringList() << "asterisk" << "details");
addIcon(0xf1fa, false, QStringList() << "at" << "e-mail" << "email");
addIcon(0xf558, false, QStringList() << "atlas" << "book" << "directions" << "geography" << "map" << "wayfinding");
addIcon(0xf5d2, false, QStringList() << "atom");
addIcon(0xf29e, false, QStringList() << "audio description");
addIcon(0xf559, false, QStringList() << "award" << "honor" << "praise" << "prize" << "recognition" << "ribbon");
addIcon(0xf55a, false, QStringList() << "backspace" << "command" << "delete" << "keyboard" << "undo");
addIcon(0xf04a, false, QStringList() << "backward" << "previous" << "rewind");
addIcon(0xf24e, false, QStringList() << "balance scale" << "balanced" << "justice" << "legal" << "measure" << "weight");
addIcon(0xf05e, false, QStringList() << "ban" << "abort" << "ban" << "block" << "cancel" << "delete" << "hide" << "prohibit" << "remove" << "stop" << "trash");
addIcon(0xf462, false, QStringList() << "band-aid" << "bandage" << "boo boo" << "ouch");
addIcon(0xf02a, false, QStringList() << "barcode" << "scan");
addIcon(0xf0c9, false, QStringList() << "bars" << "checklist" << "drag" << "hamburger" << "list" << "menu" << "nav" << "navigation" << "ol" << "reorder" << "settings" << "todo" << "ul");
addIcon(0xf433, false, QStringList() << "baseball ball");
addIcon(0xf434, false, QStringList() << "basketball ball");
addIcon(0xf2cd, false, QStringList() << "bath");
addIcon(0xf244, false, QStringList() << "battery empty" << "power" << "status");
addIcon(0xf240, false, QStringList() << "battery full" << "power" << "status");
addIcon(0xf242, false, QStringList() << "battery 1/2 full" << "power" << "status");
addIcon(0xf243, false, QStringList() << "battery 1/4 full" << "power" << "status");
addIcon(0xf241, false, QStringList() << "battery 3/4 full" << "power" << "status");
addIcon(0xf236, false, QStringList() << "bed" << "lodging" << "sleep" << "travel");
addIcon(0xf0fc, false, QStringList() << "beer" << "alcohol" << "bar" << "drink" << "liquor" << "mug" << "stein");
addIcon(0xf0f3, false, QStringList() << "bell" << "alert" << "notification" << "reminder");
addIcon(0xf1f6, false, QStringList() << "bell slash");
addIcon(0xf55b, false, QStringList() << "bezier curve" << "curves" << "illustrator" << "lines" << "path" << "vector");
addIcon(0xf206, false, QStringList() << "bicycle" << "bike" << "gears" << "transportation" << "vehicle");
addIcon(0xf1e5, false, QStringList() << "binoculars");
addIcon(0xf1fd, false, QStringList() << "birthday cake");
addIcon(0xf517, false, QStringList() << "blender");
addIcon(0xf29d, false, QStringList() << "blind");
addIcon(0xf032, false, QStringList() << "bold");
addIcon(0xf0e7, false, QStringList() << "lightning bolt" << "electricity" << "lightning" << "weather" << "zap");
addIcon(0xf1e2, false, QStringList() << "bomb");
addIcon(0xf5d7, false, QStringList() << "bone");
addIcon(0xf55c, false, QStringList() << "bong" << "aparatus" << "cannabis" << "marijuana" << "pipe" << "smoke" << "smoking");
addIcon(0xf02d, false, QStringList() << "book" << "documentation" << "read");
addIcon(0xf518, false, QStringList() << "book open" << "flyer" << "notebook" << "open book" << "pamphlet" << "reading");
addIcon(0xf5da, false, QStringList() << "book reader" << "library");
addIcon(0xf02e, false, QStringList() << "bookmark" << "save");
addIcon(0xf436, false, QStringList() << "bowling ball");
addIcon(0xf466, false, QStringList() << "box" << "package");
addIcon(0xf49e, false, QStringList() << "box open");
addIcon(0xf468, false, QStringList() << "boxes");
addIcon(0xf2a1, false, QStringList() << "braille");
addIcon(0xf5dc, false, QStringList() << "brain");
addIcon(0xf0b1, false, QStringList() << "briefcase" << "bag" << "business" << "luggage" << "office" << "work");
addIcon(0xf469, false, QStringList() << "medical briefcase" << "health briefcase");
addIcon(0xf519, false, QStringList() << "broadcast tower" << "airwaves" << "radio" << "waves");
addIcon(0xf51a, false, QStringList() << "broom");
addIcon(0xf55d, false, QStringList() << "brush" << "bristles" << "color" << "handle" << "painting");
addIcon(0xf188, false, QStringList() << "bug" << "insect" << "report");
addIcon(0xf1ad, false, QStringList() << "building" << "apartment" << "business" << "company" << "office" << "work");
addIcon(0xf0a1, false, QStringList() << "bullhorn" << "announcement" << "broadcast" << "louder" << "megaphone" << "share");
addIcon(0xf140, false, QStringList() << "bullseye" << "target");
addIcon(0xf46a, false, QStringList() << "burn" << "energy");
addIcon(0xf207, false, QStringList() << "bus" << "machine" << "public transportation" << "transportation" << "vehicle");
addIcon(0xf55e, false, QStringList() << "bus alt" << "machine" << "public transportation" << "transportation" << "vehicle");
addIcon(0xf1ec, false, QStringList() << "calculator");
addIcon(0xf133, false, QStringList() << "calendar" << "calendar-o" << "date" << "event" << "schedule" << "time" << "when");
addIcon(0xf073, false, QStringList() << "alternate calendar" << "calendar" << "date" << "event" << "schedule" << "time" << "when");
addIcon(0xf274, false, QStringList() << "calendar check" << "accept" << "agree" << "appointment" << "confirm" << "correct" << "done" << "ok" << "select" << "success" << "todo");
addIcon(0xf272, false, QStringList() << "calendar minus");
addIcon(0xf271, false, QStringList() << "calendar plus");
addIcon(0xf273, false, QStringList() << "calendar times");
addIcon(0xf030, false, QStringList() << "camera" << "photo" << "picture" << "record");
addIcon(0xf083, false, QStringList() << "retro camera" << "photo" << "picture" << "record");
addIcon(0xf55f, false, QStringList() << "cannabis" << "bud" << "chronic" << "drugs" << "endica" << "endo" << "ganja" << "marijuana" << "mary jane" << "pot" << "reefer" << "sativa" << "spliff" << "weed" << "whacky-tabacky");
addIcon(0xf46b, false, QStringList() << "capsules" << "drugs" << "medicine");
addIcon(0xf1b9, false, QStringList() << "car" << "machine" << "transportation" << "vehicle");
addIcon(0xf5de, false, QStringList() << "car alt");
addIcon(0xf5df, false, QStringList() << "car battery");
addIcon(0xf5e1, false, QStringList() << "car crash");
addIcon(0xf5e4, false, QStringList() << "car side");
addIcon(0xf0d7, false, QStringList() << "caret down" << "arrow" << "dropdown" << "menu" << "more" << "triangle down");
addIcon(0xf0d9, false, QStringList() << "caret left" << "arrow" << "back" << "previous" << "triangle left");
addIcon(0xf0da, false, QStringList() << "caret right" << "arrow" << "forward" << "next" << "triangle right");
addIcon(0xf150, false, QStringList() << "caret square down" << "caret-square-o-down" << "dropdown" << "menu" << "more");
addIcon(0xf191, false, QStringList() << "caret square left" << "back" << "caret-square-o-left" << "previous");
addIcon(0xf152, false, QStringList() << "caret square right" << "caret-square-o-right" << "forward" << "next");
addIcon(0xf151, false, QStringList() << "caret square up" << "caret-square-o-up");
addIcon(0xf0d8, false, QStringList() << "caret up" << "arrow" << "triangle up");
addIcon(0xf218, false, QStringList() << "shopping cart arrow down" << "shopping");
addIcon(0xf217, false, QStringList() << "add to shopping cart" << "add" << "shopping");
addIcon(0xf0a3, false, QStringList() << "certificate" << "badge" << "star");
addIcon(0xf51b, false, QStringList() << "chalkboard" << "blackboard" << "learning" << "school" << "teaching" << "whiteboard" << "writing");
addIcon(0xf51c, false, QStringList() << "chalkboard teacher" << "blackboard" << "instructor" << "learning" << "professor" << "school" << "whiteboard" << "writing");
addIcon(0xf5e7, false, QStringList() << "charging station");
addIcon(0xf1fe, false, QStringList() << "area chart" << "analytics" << "area-chart" << "graph");
addIcon(0xf080, false, QStringList() << "bar chart" << "analytics" << "bar-chart" << "graph");
addIcon(0xf201, false, QStringList() << "line chart" << "activity" << "analytics" << "dashboard" << "graph" << "line-chart");
addIcon(0xf200, false, QStringList() << "pie chart" << "analytics" << "graph" << "pie-chart");
addIcon(0xf00c, false, QStringList() << "check" << "accept" << "agree" << "checkmark" << "confirm" << "correct" << "done" << "notice" << "notification" << "notify" << "ok" << "select" << "success" << "tick" << "todo" << "yes");
addIcon(0xf058, false, QStringList() << "check circle" << "accept" << "agree" << "confirm" << "correct" << "done" << "ok" << "select" << "success" << "todo" << "yes");
addIcon(0xf560, false, QStringList() << "check double" << "accept" << "agree" << "checkmark" << "confirm" << "correct" << "done" << "notice" << "notification" << "notify" << "ok" << "select" << "success" << "tick" << "todo");
addIcon(0xf14a, false, QStringList() << "check square" << "accept" << "agree" << "checkmark" << "confirm" << "correct" << "done" << "ok" << "select" << "success" << "todo" << "yes");
addIcon(0xf439, false, QStringList() << "chess");
addIcon(0xf43a, false, QStringList() << "chess bishop");
addIcon(0xf43c, false, QStringList() << "chess board");
addIcon(0xf43f, false, QStringList() << "chess king");
addIcon(0xf441, false, QStringList() << "chess knight");
addIcon(0xf443, false, QStringList() << "chess pawn");
addIcon(0xf445, false, QStringList() << "chess queen");
addIcon(0xf447, false, QStringList() << "chess rook");
addIcon(0xf13a, false, QStringList() << "chevron circle down" << "arrow" << "dropdown" << "menu" << "more");
addIcon(0xf137, false, QStringList() << "chevron circle left" << "arrow" << "back" << "previous");
addIcon(0xf138, false, QStringList() << "chevron circle right" << "arrow" << "forward" << "next");
addIcon(0xf139, false, QStringList() << "chevron circle up" << "arrow");
addIcon(0xf078, false, QStringList() << "chevron-down");
addIcon(0xf053, false, QStringList() << "chevron-left" << "back" << "bracket" << "previous");
addIcon(0xf054, false, QStringList() << "chevron-right" << "bracket" << "forward" << "next");
addIcon(0xf077, false, QStringList() << "chevron-up");
addIcon(0xf1ae, false, QStringList() << "child");
addIcon(0xf51d, false, QStringList() << "church" << "building" << "community" << "religion");
addIcon(0xf111, false, QStringList() << "circle" << "circle-thin" << "dot" << "notification");
addIcon(0xf1ce, false, QStringList() << "circle notched" << "circle-o-notch");
addIcon(0xf328, false, QStringList() << "clipboard" << "paste");
addIcon(0xf46c, false, QStringList() << "clipboard check" << "accept" << "agree" << "confirm" << "done" << "ok" << "select" << "success" << "todo" << "yes");
addIcon(0xf46d, false, QStringList() << "clipboard list" << "checklist" << "completed" << "done" << "finished" << "intinerary" << "ol" << "schedule" << "todo" << "ul");
addIcon(0xf017, false, QStringList() << "clock" << "date" << "late" << "schedule" << "timer" << "timestamp" << "watch");
addIcon(0xf24d, false, QStringList() << "clone" << "copy" << "duplicate");
addIcon(0xf20a, false, QStringList() << "closed captioning" << "cc");
addIcon(0xf0c2, false, QStringList() << "cloud" << "save");
addIcon(0xf381, false, QStringList() << "alternate cloud download" << "cloud-download");
addIcon(0xf382, false, QStringList() << "alternate cloud upload" << "cloud-upload");
addIcon(0xf561, false, QStringList() << "cocktail" << "alcohol" << "drink");
addIcon(0xf121, false, QStringList() << "code" << "brackets" << "html");
addIcon(0xf126, false, QStringList() << "code branch" << "branch" << "code-fork" << "fork" << "git" << "github" << "rebase" << "svn" << "vcs" << "version");
addIcon(0xf0f4, false, QStringList() << "coffee" << "breakfast" << "cafe" << "drink" << "morning" << "mug" << "tea");
addIcon(0xf013, false, QStringList() << "cog" << "settings");
addIcon(0xf085, false, QStringList() << "cogs" << "gears" << "settings");
addIcon(0xf51e, false, QStringList() << "coins");
addIcon(0xf0db, false, QStringList() << "columns" << "dashboard" << "panes" << "split");
addIcon(0xf075, false, QStringList() << "comment" << "bubble" << "chat" << "conversation" << "feedback" << "message" << "note" << "notification" << "sms" << "speech" << "texting");
addIcon(0xf27a, false, QStringList() << "alternate comment" << "bubble" << "chat" << "commenting" << "commenting" << "conversation" << "feedback" << "message" << "note" << "notification" << "sms" << "speech" << "texting");
addIcon(0xf4ad, false, QStringList() << "comment dots");
addIcon(0xf4b3, false, QStringList() << "comment slash");
addIcon(0xf086, false, QStringList() << "comments" << "bubble" << "chat" << "conversation" << "feedback" << "message" << "note" << "notification" << "sms" << "speech" << "texting");
addIcon(0xf51f, false, QStringList() << "compact disc" << "bluray" << "cd" << "disc" << "media");
addIcon(0xf14e, false, QStringList() << "compass" << "directory" << "location" << "menu" << "safari");
addIcon(0xf066, false, QStringList() << "compress" << "collapse" << "combine" << "contract" << "merge" << "smaller");
addIcon(0xf562, false, QStringList() << "concierge bell" << "attention" << "hotel" << "service" << "support");
addIcon(0xf563, false, QStringList() << "cookie" << "baked good" << "chips" << "food" << "snack" << "sweet" << "treat");
addIcon(0xf564, false, QStringList() << "cookie bite" << "baked good" << "bitten" << "chips" << "eating" << "food" << "snack" << "sweet" << "treat");
addIcon(0xf0c5, false, QStringList() << "copy" << "clone" << "duplicate" << "file" << "files-o");
addIcon(0xf1f9, false, QStringList() << "copyright");
addIcon(0xf4b8, false, QStringList() << "couch");
addIcon(0xf09d, false, QStringList() << "credit card" << "buy" << "checkout" << "credit-card-alt" << "debit" << "money" << "payment" << "purchase");
addIcon(0xf125, false, QStringList() << "crop" << "design");
addIcon(0xf565, false, QStringList() << "alternate crop");
addIcon(0xf05b, false, QStringList() << "crosshairs" << "gpd" << "picker" << "position");
addIcon(0xf520, false, QStringList() << "crow" << "bird" << "bullfrog" << "toad");
addIcon(0xf521, false, QStringList() << "crown");
addIcon(0xf1b2, false, QStringList() << "cube" << "package");
addIcon(0xf1b3, false, QStringList() << "cubes" << "packages");
addIcon(0xf0c4, false, QStringList() << "cut" << "scissors" << "scissors");
addIcon(0xf1c0, false, QStringList() << "database");
addIcon(0xf2a4, false, QStringList() << "deaf");
addIcon(0xf108, false, QStringList() << "desktop" << "computer" << "cpu" << "demo" << "desktop" << "device" << "machine" << "monitor" << "pc" << "screen");
addIcon(0xf470, false, QStringList() << "diagnoses");
addIcon(0xf522, false, QStringList() << "dice" << "chance" << "gambling" << "game" << "roll");
addIcon(0xf523, false, QStringList() << "dice five" << "chance" << "gambling" << "game" << "roll");
addIcon(0xf524, false, QStringList() << "dice four" << "chance" << "gambling" << "game" << "roll");
addIcon(0xf525, false, QStringList() << "dice one" << "chance" << "gambling" << "game" << "roll");
addIcon(0xf526, false, QStringList() << "dice six" << "chance" << "gambling" << "game" << "roll");
addIcon(0xf527, false, QStringList() << "dice three" << "chance" << "gambling" << "game" << "roll");
addIcon(0xf528, false, QStringList() << "dice two" << "chance" << "gambling" << "game" << "roll");
addIcon(0xf566, false, QStringList() << "digital tachograph");
addIcon(0xf5eb, false, QStringList() << "directions");
addIcon(0xf529, false, QStringList() << "divide");
addIcon(0xf567, false, QStringList() << "dizzy face" << "dazed" << "disapprove" << "emoticon" << "face");
addIcon(0xf471, false, QStringList() << "dna" << "double helix" << "helix");
addIcon(0xf155, false, QStringList() << "dollar sign" << "$" << "dollar-sign" << "money" << "price" << "usd");
addIcon(0xf472, false, QStringList() << "dolly");
addIcon(0xf474, false, QStringList() << "dolly flatbed");
addIcon(0xf4b9, false, QStringList() << "donate" << "generosity" << "give");
addIcon(0xf52a, false, QStringList() << "door closed");
addIcon(0xf52b, false, QStringList() << "door open");
addIcon(0xf192, false, QStringList() << "dot circle" << "bullseye" << "notification" << "target");
addIcon(0xf4ba, false, QStringList() << "dove");
addIcon(0xf019, false, QStringList() << "download" << "import");
addIcon(0xf568, false, QStringList() << "drafting compass" << "mechanical drawing" << "plot" << "plotting");
addIcon(0xf5ee, false, QStringList() << "draw polygon");
addIcon(0xf569, false, QStringList() << "drum" << "instrument" << "music" << "percussion" << "snare" << "sound");
addIcon(0xf56a, false, QStringList() << "drum steelpan" << "calypso" << "instrument" << "music" << "percussion" << "reggae" << "snare" << "sound" << "steel" << "tropical");
addIcon(0xf44b, false, QStringList() << "dumbbell" << "exercise" << "gym" << "strength" << "weight" << "weight-lifting");
addIcon(0xf044, false, QStringList() << "edit" << "edit" << "pen" << "pencil" << "update" << "write");
addIcon(0xf052, false, QStringList() << "eject");
addIcon(0xf141, false, QStringList() << "horizontal ellipsis" << "dots" << "drag" << "kebab" << "list" << "menu" << "nav" << "navigation" << "ol" << "reorder" << "settings" << "ul");
addIcon(0xf142, false, QStringList() << "vertical ellipsis" << "dots" << "drag" << "kebab" << "list" << "menu" << "nav" << "navigation" << "ol" << "reorder" << "settings" << "ul");
addIcon(0xf0e0, false, QStringList() << "envelope" << "e-mail" << "email" << "letter" << "mail" << "message" << "notification" << "support");
addIcon(0xf2b6, false, QStringList() << "envelope open" << "e-mail" << "email" << "letter" << "mail" << "message" << "notification" << "support");
addIcon(0xf199, false, QStringList() << "envelope square" << "e-mail" << "email" << "letter" << "mail" << "message" << "notification" << "support");
addIcon(0xf52c, false, QStringList() << "equals");
addIcon(0xf12d, false, QStringList() << "eraser" << "delete" << "remove");
addIcon(0xf153, false, QStringList() << "euro sign" << "eur" << "eur");
addIcon(0xf362, false, QStringList() << "alternate exchange" << "arrow" << "arrows" << "exchange" << "reciprocate" << "return" << "swap" << "transfer");
addIcon(0xf12a, false, QStringList() << "exclamation" << "alert" << "danger" << "error" << "important" << "notice" << "notification" << "notify" << "problem" << "warning");
addIcon(0xf06a, false, QStringList() << "exclamation circle" << "alert" << "danger" << "error" << "important" << "notice" << "notification" << "notify" << "problem" << "warning");
addIcon(0xf071, false, QStringList() << "exclamation triangle" << "alert" << "danger" << "error" << "important" << "notice" << "notification" << "notify" << "problem" << "warning");
addIcon(0xf065, false, QStringList() << "expand" << "bigger" << "enlarge" << "resize");
addIcon(0xf31e, false, QStringList() << "alternate expand arrows" << "arrows-alt" << "bigger" << "enlarge" << "move" << "resize");
addIcon(0xf35d, false, QStringList() << "alternate external link" << "external-link" << "new" << "open");
addIcon(0xf360, false, QStringList() << "alternate external link square" << "external-link-square" << "new" << "open");
addIcon(0xf06e, false, QStringList() << "eye" << "optic" << "see" << "seen" << "show" << "sight" << "views" << "visible");
addIcon(0xf1fb, false, QStringList() << "eye dropper" << "eyedropper");
addIcon(0xf070, false, QStringList() << "eye slash" << "blind" << "hide" << "show" << "toggle" << "unseen" << "views" << "visible" << "visiblity");
addIcon(0xf049, false, QStringList() << "fast-backward" << "beginning" << "first" << "previous" << "rewind" << "start");
addIcon(0xf050, false, QStringList() << "fast-forward" << "end" << "last" << "next");
addIcon(0xf1ac, false, QStringList() << "fax");
addIcon(0xf52d, false, QStringList() << "feather" << "bird" << "light" << "plucked" << "quill");
addIcon(0xf56b, false, QStringList() << "feather alt" << "bird" << "light" << "plucked" << "quill");
addIcon(0xf182, false, QStringList() << "female" << "human" << "person" << "profile" << "user" << "woman");
addIcon(0xf0fb, false, QStringList() << "fighter-jet" << "airplane" << "fast" << "fly" << "goose" << "maverick" << "plane" << "quick" << "top gun" << "transportation" << "travel");
addIcon(0xf15b, false, QStringList() << "file" << "document" << "new" << "page" << "pdf" << "resume");
addIcon(0xf15c, false, QStringList() << "alternate file" << "document" << "file-text" << "invoice" << "new" << "page" << "pdf");
addIcon(0xf1c6, false, QStringList() << "archive file" << ".zip" << "bundle" << "compress" << "compression" << "download" << "zip");
addIcon(0xf1c7, false, QStringList() << "audio file");
addIcon(0xf1c9, false, QStringList() << "code file");
addIcon(0xf56c, false, QStringList() << "file contract" << "agreement" << "binding" << "document" << "legal" << "signature");
addIcon(0xf56d, false, QStringList() << "file download");
addIcon(0xf1c3, false, QStringList() << "excel file");
addIcon(0xf56e, false, QStringList() << "file export");
addIcon(0xf1c5, false, QStringList() << "image file");
addIcon(0xf56f, false, QStringList() << "file import");
addIcon(0xf570, false, QStringList() << "file invoice" << "bill" << "document" << "receipt");
addIcon(0xf571, false, QStringList() << "file invoice with us dollar" << "$" << "bill" << "document" << "dollar-sign" << "money" << "receipt" << "usd");
addIcon(0xf477, false, QStringList() << "medical file");
addIcon(0xf478, false, QStringList() << "alternate medical file");
addIcon(0xf1c1, false, QStringList() << "pdf file");
addIcon(0xf1c4, false, QStringList() << "powerpoint file");
addIcon(0xf572, false, QStringList() << "file prescription" << "drugs" << "medical" << "medicine" << "rx");
addIcon(0xf573, false, QStringList() << "file signature" << "John Hancock" << "contract" << "document" << "name");
addIcon(0xf574, false, QStringList() << "file upload");
addIcon(0xf1c8, false, QStringList() << "video file");
addIcon(0xf1c2, false, QStringList() << "word file");
addIcon(0xf575, false, QStringList() << "fill" << "bucket" << "color" << "paint" << "paint bucket");
addIcon(0xf576, false, QStringList() << "fill drip" << "bucket" << "color" << "drop" << "paint" << "paint bucket" << "spill");
addIcon(0xf008, false, QStringList() << "film" << "movie");
addIcon(0xf0b0, false, QStringList() << "filter" << "funnel" << "options");
addIcon(0xf577, false, QStringList() << "fingerprint" << "human" << "id" << "identification" << "lock" << "smudge" << "touch" << "unique" << "unlock");
addIcon(0xf06d, false, QStringList() << "fire" << "flame" << "hot" << "popular");
addIcon(0xf134, false, QStringList() << "fire-extinguisher");
addIcon(0xf479, false, QStringList() << "first aid");
addIcon(0xf578, false, QStringList() << "fish");
addIcon(0xf024, false, QStringList() << "flag" << "notice" << "notification" << "notify" << "report");
addIcon(0xf11e, false, QStringList() << "flag-checkered" << "notice" << "notification" << "notify" << "report");
addIcon(0xf0c3, false, QStringList() << "flask" << "beaker" << "experimental" << "labs" << "science");
addIcon(0xf579, false, QStringList() << "flushed face" << "embarrassed" << "emoticon" << "face");
addIcon(0xf07b, false, QStringList() << "folder");
addIcon(0xf07c, false, QStringList() << "folder open");
addIcon(0xf031, false, QStringList() << "font" << "text");
addIcon(0xf4e6, false, QStringList() << "font awesome full logo");
addIcon(0xf44e, false, QStringList() << "football ball");
addIcon(0xf04e, false, QStringList() << "forward" << "forward" << "next");
addIcon(0xf52e, false, QStringList() << "frog" << "bullfrog" << "kermit" << "kiss" << "prince" << "toad" << "wart");
addIcon(0xf119, false, QStringList() << "frowning face" << "disapprove" << "emoticon" << "face" << "rating" << "sad");
addIcon(0xf57a, false, QStringList() << "frowning face with open mouth" << "disapprove" << "emoticon" << "face" << "rating" << "sad");
addIcon(0xf1e3, false, QStringList() << "futbol" << "ball" << "football" << "soccer");
addIcon(0xf11b, false, QStringList() << "gamepad" << "controller");
addIcon(0xf52f, false, QStringList() << "gas pump");
addIcon(0xf0e3, false, QStringList() << "gavel" << "hammer" << "judge" << "lawyer" << "opinion");
addIcon(0xf3a5, false, QStringList() << "gem" << "diamond");
addIcon(0xf22d, false, QStringList() << "genderless");
addIcon(0xf06b, false, QStringList() << "gift" << "generosity" << "giving" << "party" << "present" << "wrapped");
addIcon(0xf000, false, QStringList() << "martini glass" << "alcohol" << "bar" << "drink" << "glass" << "liquor" << "martini");
addIcon(0xf57b, false, QStringList() << "glass martini-alt");
addIcon(0xf530, false, QStringList() << "glasses" << "foureyes" << "hipster" << "nerd" << "reading" << "sight" << "spectacles");
addIcon(0xf0ac, false, QStringList() << "globe" << "all" << "coordinates" << "country" << "earth" << "global" << "gps" << "language" << "localize" << "location" << "map" << "online" << "place" << "planet" << "translate" << "travel" << "world");
addIcon(0xf57c, false, QStringList() << "globe with africa shown" << "all" << "country" << "earth" << "global" << "gps" << "language" << "localize" << "location" << "map" << "online" << "place" << "planet" << "translate" << "travel" << "world");
addIcon(0xf57d, false, QStringList() << "globe with americas shown" << "all" << "country" << "earth" << "global" << "gps" << "language" << "localize" << "location" << "map" << "online" << "place" << "planet" << "translate" << "travel" << "world");
addIcon(0xf57e, false, QStringList() << "globe with asia shown" << "all" << "country" << "earth" << "global" << "gps" << "language" << "localize" << "location" << "map" << "online" << "place" << "planet" << "translate" << "travel" << "world");
addIcon(0xf450, false, QStringList() << "golf ball");
addIcon(0xf19d, false, QStringList() << "graduation cap" << "learning" << "school" << "student");
addIcon(0xf531, false, QStringList() << "greater than");
addIcon(0xf532, false, QStringList() << "greater than equal to");
addIcon(0xf57f, false, QStringList() << "grimacing face" << "cringe" << "emoticon" << "face");
addIcon(0xf580, false, QStringList() << "grinning face" << "emoticon" << "face" << "laugh" << "smile");
addIcon(0xf581, false, QStringList() << "alternate grinning face" << "emoticon" << "face" << "laugh" << "smile");
addIcon(0xf582, false, QStringList() << "grinning face with smiling eyes" << "emoticon" << "face" << "laugh" << "smile");
addIcon(0xf583, false, QStringList() << "grinning face with sweat" << "emoticon" << "face" << "smile");
addIcon(0xf584, false, QStringList() << "smiling face with heart-eyes" << "emoticon" << "face" << "love" << "smile");
addIcon(0xf585, false, QStringList() << "grinning squinting face" << "emoticon" << "face" << "laugh" << "smile");
addIcon(0xf586, false, QStringList() << "rolling on the floor laughing" << "emoticon" << "face" << "happy" << "smile");
addIcon(0xf587, false, QStringList() << "star-struck" << "emoticon" << "face" << "star-struck");
addIcon(0xf588, false, QStringList() << "face with tears of joy" << "LOL" << "emoticon" << "face");
addIcon(0xf589, false, QStringList() << "face with tongue" << "LOL" << "emoticon" << "face");
addIcon(0xf58a, false, QStringList() << "squinting face with tongue" << "LOL" << "emoticon" << "face");
addIcon(0xf58b, false, QStringList() << "winking face with tongue" << "LOL" << "emoticon" << "face");
addIcon(0xf58c, false, QStringList() << "grinning winking face" << "emoticon" << "face" << "flirt" << "laugh" << "smile");
addIcon(0xf58d, false, QStringList() << "grip horizontal" << "affordance" << "drag" << "drop" << "grab" << "handle");
addIcon(0xf58e, false, QStringList() << "grip vertical" << "affordance" << "drag" << "drop" << "grab" << "handle");
addIcon(0xf0fd, false, QStringList() << "h square" << "hospital" << "hotel");
addIcon(0xf4bd, false, QStringList() << "hand holding");
addIcon(0xf4be, false, QStringList() << "hand holding heart");
addIcon(0xf4c0, false, QStringList() << "hand holding us dollar" << "$" << "dollar sign" << "donation" << "giving" << "money" << "price");
addIcon(0xf258, false, QStringList() << "lizard (hand)");
addIcon(0xf256, false, QStringList() << "paper (hand)" << "stop");
addIcon(0xf25b, false, QStringList() << "peace (hand)");
addIcon(0xf0a7, false, QStringList() << "hand pointing down" << "finger" << "hand-o-down" << "point");
addIcon(0xf0a5, false, QStringList() << "hand pointing left" << "back" << "finger" << "hand-o-left" << "left" << "point" << "previous");
addIcon(0xf0a4, false, QStringList() << "hand pointing right" << "finger" << "forward" << "hand-o-right" << "next" << "point" << "right");
addIcon(0xf0a6, false, QStringList() << "hand pointing up" << "finger" << "hand-o-up" << "point");
addIcon(0xf25a, false, QStringList() << "pointer (hand)" << "select");
addIcon(0xf255, false, QStringList() << "rock (hand)");
addIcon(0xf257, false, QStringList() << "scissors (hand)");
addIcon(0xf259, false, QStringList() << "spock (hand)");
addIcon(0xf4c2, false, QStringList() << "hands");
addIcon(0xf4c4, false, QStringList() << "helping hands" << "aid" << "assistance" << "partnership" << "volunteering");
addIcon(0xf2b5, false, QStringList() << "handshake" << "greeting" << "partnership");
addIcon(0xf292, false, QStringList() << "hashtag");
addIcon(0xf0a0, false, QStringList() << "hdd" << "cpu" << "hard drive" << "harddrive" << "machine" << "save" << "storage");
addIcon(0xf1dc, false, QStringList() << "heading" << "header" << "header");
addIcon(0xf025, false, QStringList() << "headphones" << "audio" << "listen" << "music" << "sound" << "speaker");
addIcon(0xf58f, false, QStringList() << "headphones alt" << "audio" << "listen" << "music" << "sound" << "speaker");
addIcon(0xf590, false, QStringList() << "headset" << "audio" << "gamer" << "gaming" << "listen" << "live chat" << "microphone" << "shot caller" << "sound" << "support" << "telemarketer");
addIcon(0xf004, false, QStringList() << "heart" << "favorite" << "like" << "love");
addIcon(0xf21e, false, QStringList() << "heartbeat" << "ekg" << "lifeline" << "vital signs");
addIcon(0xf533, false, QStringList() << "helicopter" << "airwolf" << "apache" << "chopper" << "flight" << "fly");
addIcon(0xf591, false, QStringList() << "highlighter" << "edit" << "marker" << "sharpie" << "update" << "write");
addIcon(0xf1da, false, QStringList() << "history");
addIcon(0xf453, false, QStringList() << "hockey puck");
addIcon(0xf015, false, QStringList() << "home" << "house" << "main");
addIcon(0xf0f8, false, QStringList() << "hospital" << "building" << "emergency room" << "medical center");
addIcon(0xf47d, false, QStringList() << "alternate hospital" << "building" << "emergency room" << "medical center");
addIcon(0xf47e, false, QStringList() << "hospital symbol");
addIcon(0xf593, false, QStringList() << "hot tub");
addIcon(0xf594, false, QStringList() << "hotel" << "building" << "lodging");
addIcon(0xf254, false, QStringList() << "hourglass");
addIcon(0xf253, false, QStringList() << "hourglass end");
addIcon(0xf252, false, QStringList() << "hourglass half");
addIcon(0xf251, false, QStringList() << "hourglass start");
addIcon(0xf246, false, QStringList() << "i beam cursor");
addIcon(0xf2c1, false, QStringList() << "identification badge");
addIcon(0xf2c2, false, QStringList() << "identification card" << "document" << "identification" << "issued");
addIcon(0xf47f, false, QStringList() << "alternate identification card" << "demographics");
addIcon(0xf03e, false, QStringList() << "image" << "album" << "photo" << "picture" << "picture");
addIcon(0xf302, false, QStringList() << "images" << "album" << "photo" << "picture");
addIcon(0xf01c, false, QStringList() << "inbox");
addIcon(0xf03c, false, QStringList() << "indent");
addIcon(0xf275, false, QStringList() << "industry" << "factory" << "manufacturing");
addIcon(0xf534, false, QStringList() << "infinity");
addIcon(0xf129, false, QStringList() << "info" << "details" << "help" << "information" << "more");
addIcon(0xf05a, false, QStringList() << "info circle" << "details" << "help" << "information" << "more");
addIcon(0xf033, false, QStringList() << "italic" << "italics");
addIcon(0xf595, false, QStringList() << "joint" << "blunt" << "cannabis" << "doobie" << "drugs" << "marijuana" << "roach" << "smoke" << "smoking" << "spliff");
addIcon(0xf084, false, QStringList() << "key" << "password" << "unlock");
addIcon(0xf11c, false, QStringList() << "keyboard" << "input" << "type");
addIcon(0xf596, false, QStringList() << "kissing face" << "beso" << "emoticon" << "face" << "love" << "smooch");
addIcon(0xf597, false, QStringList() << "kissing face with smiling eyes" << "beso" << "emoticon" << "face" << "love" << "smooch");
addIcon(0xf598, false, QStringList() << "face blowing a kiss" << "beso" << "emoticon" << "face" << "love" << "smooch");
addIcon(0xf535, false, QStringList() << "kiwi bird");
addIcon(0xf1ab, false, QStringList() << "language" << "dialect" << "idiom" << "localize" << "speech" << "translate" << "vernacular");
addIcon(0xf109, false, QStringList() << "laptop" << "computer" << "cpu" << "dell" << "demo" << "device" << "dude you're getting" << "mac" << "macbook" << "machine" << "pc" << "pc");
addIcon(0xf5fc, false, QStringList() << "laptop code");
addIcon(0xf599, false, QStringList() << "grinning face with big eyes" << "LOL" << "emoticon" << "face" << "laugh");
addIcon(0xf59a, false, QStringList() << "laugh face with beaming eyes" << "LOL" << "emoticon" << "face");
addIcon(0xf59b, false, QStringList() << "laughing squinting face" << "LOL" << "emoticon" << "face");
addIcon(0xf59c, false, QStringList() << "laughing winking face" << "LOL" << "emoticon" << "face");
addIcon(0xf5fd, false, QStringList() << "layer group" << "layers");
addIcon(0xf06c, false, QStringList() << "leaf" << "eco" << "nature" << "plant");
addIcon(0xf094, false, QStringList() << "lemon" << "food");
addIcon(0xf536, false, QStringList() << "less than");
addIcon(0xf537, false, QStringList() << "less than equal to");
addIcon(0xf3be, false, QStringList() << "alternate level down" << "level-down");
addIcon(0xf3bf, false, QStringList() << "alternate level up" << "level-up");
addIcon(0xf1cd, false, QStringList() << "life ring" << "support");
addIcon(0xf0eb, false, QStringList() << "lightbulb" << "idea" << "inspiration");
addIcon(0xf0c1, false, QStringList() << "link" << "chain");
addIcon(0xf195, false, QStringList() << "turkish lira sign" << "try" << "try" << "turkish");
addIcon(0xf03a, false, QStringList() << "list" << "checklist" << "completed" << "done" << "finished" << "ol" << "todo" << "ul");
addIcon(0xf022, false, QStringList() << "alternate list" << "checklist" << "completed" << "done" << "finished" << "ol" << "todo" << "ul");
addIcon(0xf0cb, false, QStringList() << "list-ol" << "checklist" << "list" << "list" << "numbers" << "ol" << "todo" << "ul");
addIcon(0xf0ca, false, QStringList() << "list-ul" << "checklist" << "list" << "ol" << "todo" << "ul");
addIcon(0xf124, false, QStringList() << "location-arrow" << "address" << "coordinates" << "gps" << "location" << "map" << "place" << "where");
addIcon(0xf023, false, QStringList() << "lock" << "admin" << "protect" << "security");
addIcon(0xf3c1, false, QStringList() << "lock open" << "admin" << "lock" << "open" << "password" << "protect");
addIcon(0xf309, false, QStringList() << "alternate long arrow down" << "long-arrow-down");
addIcon(0xf30a, false, QStringList() << "alternate long arrow left" << "back" << "long-arrow-left" << "previous");
addIcon(0xf30b, false, QStringList() << "alternate long arrow right" << "long-arrow-right");
addIcon(0xf30c, false, QStringList() << "alternate long arrow up" << "long-arrow-up");
addIcon(0xf2a8, false, QStringList() << "low vision");
addIcon(0xf59d, false, QStringList() << "luggage cart");
addIcon(0xf0d0, false, QStringList() << "magic" << "autocomplete" << "automatic" << "wizard");
addIcon(0xf076, false, QStringList() << "magnet");
addIcon(0xf183, false, QStringList() << "male" << "human" << "man" << "person" << "profile" << "user");
addIcon(0xf279, false, QStringList() << "map" << "coordinates" << "location" << "paper" << "place" << "travel");
addIcon(0xf59f, false, QStringList() << "map marked" << "address" << "coordinates" << "destination" << "gps" << "localize" << "location" << "map" << "paper" << "pin" << "place" << "point of interest" << "position" << "route" << "travel" << "where");
addIcon(0xf5a0, false, QStringList() << "map marked-alt" << "address" << "coordinates" << "destination" << "gps" << "localize" << "location" << "map" << "paper" << "pin" << "place" << "point of interest" << "position" << "route" << "travel" << "where");
addIcon(0xf041, false, QStringList() << "map-marker" << "address" << "coordinates" << "gps" << "localize" << "location" << "map" << "pin" << "place" << "position" << "travel" << "where");
addIcon(0xf3c5, false, QStringList() << "alternate map marker" << "address" << "coordinates" << "gps" << "localize" << "location" << "map" << "pin" << "place" << "position" << "travel" << "where");
addIcon(0xf276, false, QStringList() << "map pin" << "address" << "coordinates" << "gps" << "localize" << "location" << "map" << "marker" << "place" << "position" << "travel" << "where");
addIcon(0xf277, false, QStringList() << "map signs");
addIcon(0xf5a1, false, QStringList() << "marker" << "edit" << "sharpie" << "update" << "write");
addIcon(0xf222, false, QStringList() << "mars" << "male");
addIcon(0xf227, false, QStringList() << "mars double");
addIcon(0xf229, false, QStringList() << "mars stroke");
addIcon(0xf22b, false, QStringList() << "mars stroke horizontal");
addIcon(0xf22a, false, QStringList() << "mars stroke vertical");
addIcon(0xf5a2, false, QStringList() << "medal");
addIcon(0xf0fa, false, QStringList() << "medkit" << "first aid" << "firstaid" << "health" << "help" << "support");
addIcon(0xf11a, false, QStringList() << "neutral face" << "emoticon" << "face" << "neutral" << "rating");
addIcon(0xf5a4, false, QStringList() << "face without mouth" << "emoticon" << "face" << "neutral" << "rating");
addIcon(0xf5a5, false, QStringList() << "face with rolling eyes" << "emoticon" << "face" << "neutral" << "rating");
addIcon(0xf538, false, QStringList() << "memory" << "DIMM" << "RAM");
addIcon(0xf223, false, QStringList() << "mercury" << "transgender");
addIcon(0xf2db, false, QStringList() << "microchip" << "cpu" << "processor");
addIcon(0xf130, false, QStringList() << "microphone" << "record" << "sound" << "voice");
addIcon(0xf3c9, false, QStringList() << "alternate microphone" << "record" << "sound" << "voice");
addIcon(0xf539, false, QStringList() << "alternate microphone slash" << "disable" << "mute" << "record" << "sound" << "voice");
addIcon(0xf131, false, QStringList() << "microphone slash" << "disable" << "mute" << "record" << "sound" << "voice");
addIcon(0xf610, false, QStringList() << "microscope");
addIcon(0xf068, false, QStringList() << "minus" << "collapse" << "delete" << "hide" << "hide" << "minify" << "remove" << "trash");
addIcon(0xf056, false, QStringList() << "minus circle" << "delete" << "hide" << "remove" << "trash");
addIcon(0xf146, false, QStringList() << "minus square" << "collapse" << "delete" << "hide" << "hide" << "minify" << "remove" << "trash");
addIcon(0xf10b, false, QStringList() << "mobile phone" << "apple" << "call" << "cell phone" << "cellphone" << "device" << "iphone" << "number" << "screen" << "telephone" << "text");
addIcon(0xf3cd, false, QStringList() << "alternate mobile" << "apple" << "call" << "cell phone" << "cellphone" << "device" << "iphone" << "number" << "screen" << "telephone" << "text");
addIcon(0xf0d6, false, QStringList() << "money bill" << "buy" << "cash" << "checkout" << "money" << "payment" << "price" << "purchase");
addIcon(0xf3d1, false, QStringList() << "alternate money bill" << "buy" << "cash" << "checkout" << "money" << "payment" << "price" << "purchase");
addIcon(0xf53a, false, QStringList() << "wavy money bill");
addIcon(0xf53b, false, QStringList() << "alternate wavy money bill");
addIcon(0xf53c, false, QStringList() << "money check" << "bank check" << "cheque");
addIcon(0xf53d, false, QStringList() << "alternate money check" << "bank check" << "cheque");
addIcon(0xf5a6, false, QStringList() << "monument" << "building" << "historic" << "memoroable");
addIcon(0xf186, false, QStringList() << "moon" << "contrast" << "darker" << "night");
addIcon(0xf5a7, false, QStringList() << "mortar pestle" << "crush" << "culinary" << "grind" << "medical" << "mix" << "spices");
addIcon(0xf21c, false, QStringList() << "motorcycle" << "bike" << "machine" << "transportation" << "vehicle");
addIcon(0xf245, false, QStringList() << "mouse pointer" << "select");
addIcon(0xf001, false, QStringList() << "music" << "note" << "sound");
addIcon(0xf22c, false, QStringList() << "neuter");
addIcon(0xf1ea, false, QStringList() << "newspaper" << "article" << "press");
addIcon(0xf53e, false, QStringList() << "not equal");
addIcon(0xf481, false, QStringList() << "medical notes");
addIcon(0xf247, false, QStringList() << "object group" << "design");
addIcon(0xf248, false, QStringList() << "object ungroup" << "design");
addIcon(0xf613, false, QStringList() << "oil can");
addIcon(0xf03b, false, QStringList() << "outdent");
addIcon(0xf1fc, false, QStringList() << "paint brush");
addIcon(0xf5aa, false, QStringList() << "paint roller" << "brush" << "painting" << "tool");
addIcon(0xf53f, false, QStringList() << "palette" << "colors" << "painting");
addIcon(0xf482, false, QStringList() << "pallet");
addIcon(0xf1d8, false, QStringList() << "paper plane");
addIcon(0xf0c6, false, QStringList() << "paperclip" << "attachment");
addIcon(0xf4cd, false, QStringList() << "parachute box" << "aid" << "assistance" << "rescue" << "supplies");
addIcon(0xf1dd, false, QStringList() << "paragraph");
addIcon(0xf540, false, QStringList() << "parking");
addIcon(0xf5ab, false, QStringList() << "passport" << "document" << "identification" << "issued");
addIcon(0xf0ea, false, QStringList() << "paste" << "clipboard" << "copy");
addIcon(0xf04c, false, QStringList() << "pause" << "wait");
addIcon(0xf28b, false, QStringList() << "pause circle");
addIcon(0xf1b0, false, QStringList() << "paw" << "pet");
addIcon(0xf304, false, QStringList() << "pen" << "design" << "edit" << "update" << "write");
addIcon(0xf305, false, QStringList() << "alternate pen" << "design" << "edit" << "update" << "write");
addIcon(0xf5ac, false, QStringList() << "pen fancy" << "design" << "edit" << "fountain pen" << "update" << "write");
addIcon(0xf5ad, false, QStringList() << "pen nib" << "design" << "edit" << "fountain pen" << "update" << "write");
addIcon(0xf14b, false, QStringList() << "pen square" << "edit" << "pencil-square" << "update" << "write");
addIcon(0xf303, false, QStringList() << "alternate pencil" << "design" << "edit" << "pencil" << "update" << "write");
addIcon(0xf5ae, false, QStringList() << "pencil ruler");
addIcon(0xf4ce, false, QStringList() << "people carry" << "movers");
addIcon(0xf295, false, QStringList() << "percent");
addIcon(0xf541, false, QStringList() << "percentage");
addIcon(0xf095, false, QStringList() << "phone" << "call" << "earphone" << "number" << "support" << "telephone" << "voice");
addIcon(0xf3dd, false, QStringList() << "phone slash");
addIcon(0xf098, false, QStringList() << "phone square" << "call" << "number" << "support" << "telephone" << "voice");
addIcon(0xf2a0, false, QStringList() << "phone volume" << "telephone" << "volume-control-phone");
addIcon(0xf4d3, false, QStringList() << "piggy bank" << "save" << "savings");
addIcon(0xf484, false, QStringList() << "pills" << "drugs" << "medicine");
addIcon(0xf072, false, QStringList() << "plane" << "airplane" << "destination" << "fly" << "location" << "mode" << "travel" << "trip");
addIcon(0xf5af, false, QStringList() << "plane arrival" << "airplane" << "arriving" << "destination" << "fly" << "land" << "landing" << "location" << "mode" << "travel" << "trip");
addIcon(0xf5b0, false, QStringList() << "plane departure" << "airplane" << "departing" << "destination" << "fly" << "location" << "mode" << "take off" << "taking off" << "travel" << "trip");
addIcon(0xf04b, false, QStringList() << "play" << "music" << "playing" << "sound" << "start");
addIcon(0xf144, false, QStringList() << "play circle" << "playing" << "start");
addIcon(0xf1e6, false, QStringList() << "plug" << "connect" << "online" << "power");
addIcon(0xf067, false, QStringList() << "plus" << "add" << "create" << "expand" << "new");
addIcon(0xf055, false, QStringList() << "plus circle" << "add" << "create" << "expand" << "new");
addIcon(0xf0fe, false, QStringList() << "plus square" << "add" << "create" << "expand" << "new");
addIcon(0xf2ce, false, QStringList() << "podcast");
addIcon(0xf2fe, false, QStringList() << "poo");
addIcon(0xf619, false, QStringList() << "poop");
addIcon(0xf3e0, false, QStringList() << "portrait");
addIcon(0xf154, false, QStringList() << "pound sign" << "gbp" << "gbp");
addIcon(0xf011, false, QStringList() << "power off" << "on" << "reboot" << "restart");
addIcon(0xf5b1, false, QStringList() << "prescription" << "drugs" << "medical" << "medicine" << "rx");
addIcon(0xf485, false, QStringList() << "prescription bottle" << "drugs" << "medical" << "medicine" << "rx");
addIcon(0xf486, false, QStringList() << "alternate prescription bottle" << "drugs" << "medical" << "medicine" << "rx");
addIcon(0xf02f, false, QStringList() << "print");
addIcon(0xf487, false, QStringList() << "procedures");
addIcon(0xf542, false, QStringList() << "project diagram");
addIcon(0xf12e, false, QStringList() << "puzzle piece" << "add-on" << "addon" << "section");
addIcon(0xf029, false, QStringList() << "qrcode" << "scan");
addIcon(0xf128, false, QStringList() << "question" << "help" << "information" << "support" << "unknown");
addIcon(0xf059, false, QStringList() << "question circle" << "help" << "information" << "support" << "unknown");
addIcon(0xf458, false, QStringList() << "quidditch");
addIcon(0xf10d, false, QStringList() << "quote-left");
addIcon(0xf10e, false, QStringList() << "quote-right");
addIcon(0xf074, false, QStringList() << "random" << "shuffle" << "sort");
addIcon(0xf543, false, QStringList() << "receipt" << "check" << "invoice" << "table");
addIcon(0xf1b8, false, QStringList() << "recycle");
addIcon(0xf01e, false, QStringList() << "redo" << "forward" << "repeat" << "repeat");
addIcon(0xf2f9, false, QStringList() << "alternate redo" << "forward" << "repeat");
addIcon(0xf25d, false, QStringList() << "registered trademark");
addIcon(0xf3e5, false, QStringList() << "reply");
addIcon(0xf122, false, QStringList() << "reply-all");
addIcon(0xf079, false, QStringList() << "retweet" << "refresh" << "reload" << "share" << "swap");
addIcon(0xf4d6, false, QStringList() << "ribbon" << "badge" << "cause" << "lapel" << "pin");
addIcon(0xf018, false, QStringList() << "road" << "street");
addIcon(0xf544, false, QStringList() << "robot");
addIcon(0xf135, false, QStringList() << "rocket" << "app");
addIcon(0xf4d7, false, QStringList() << "route");
addIcon(0xf09e, false, QStringList() << "rss" << "blog");
addIcon(0xf143, false, QStringList() << "rss square" << "blog" << "feed");
addIcon(0xf158, false, QStringList() << "ruble sign" << "rub" << "rub");
addIcon(0xf545, false, QStringList() << "ruler");
addIcon(0xf546, false, QStringList() << "ruler combined");
addIcon(0xf547, false, QStringList() << "ruler horizontal");
addIcon(0xf548, false, QStringList() << "ruler vertical");
addIcon(0xf156, false, QStringList() << "indian rupee sign" << "indian" << "inr");
addIcon(0xf5b3, false, QStringList() << "crying face" << "emoticon" << "face" << "tear" << "tears");
addIcon(0xf5b4, false, QStringList() << "loudly crying face" << "emoticon" << "face" << "tear" << "tears");
addIcon(0xf0c7, false, QStringList() << "save" << "floppy" << "floppy-o");
addIcon(0xf549, false, QStringList() << "school");
addIcon(0xf54a, false, QStringList() << "screwdriver" << "admin" << "container" << "fix" << "repair" << "settings" << "tool");
addIcon(0xf002, false, QStringList() << "search" << "bigger" << "enlarge" << "magnify" << "preview" << "zoom");
addIcon(0xf010, false, QStringList() << "search minus" << "magnify" << "minify" << "smaller" << "zoom" << "zoom out");
addIcon(0xf00e, false, QStringList() << "search plus" << "bigger" << "enlarge" << "magnify" << "zoom" << "zoom in");
addIcon(0xf4d8, false, QStringList() << "seedling");
addIcon(0xf233, false, QStringList() << "server" << "cpu");
addIcon(0xf61f, false, QStringList() << "shapes" << "circle" << "square" << "triangle");
addIcon(0xf064, false, QStringList() << "share");
addIcon(0xf1e0, false, QStringList() << "alternate share");
addIcon(0xf1e1, false, QStringList() << "alternate share square");
addIcon(0xf14d, false, QStringList() << "share square" << "send" << "social");
addIcon(0xf20b, false, QStringList() << "shekel sign" << "ils" << "ils");
addIcon(0xf3ed, false, QStringList() << "alternate shield" << "shield");
addIcon(0xf21a, false, QStringList() << "ship" << "boat" << "sea");
addIcon(0xf48b, false, QStringList() << "shipping fast");
addIcon(0xf54b, false, QStringList() << "shoe prints" << "feet" << "footprints" << "steps");
addIcon(0xf290, false, QStringList() << "shopping bag");
addIcon(0xf291, false, QStringList() << "shopping basket");
addIcon(0xf07a, false, QStringList() << "shopping-cart" << "buy" << "checkout" << "payment" << "purchase");
addIcon(0xf2cc, false, QStringList() << "shower");
addIcon(0xf5b6, false, QStringList() << "shuttle van" << "machine" << "public-transportation" << "transportation" << "vehicle");
addIcon(0xf4d9, false, QStringList() << "sign");
addIcon(0xf2f6, false, QStringList() << "alternate sign in" << "arrow" << "enter" << "join" << "log in" << "login" << "sign in" << "sign up" << "sign-in" << "signin" << "signup");
addIcon(0xf2a7, false, QStringList() << "sign language");
addIcon(0xf2f5, false, QStringList() << "alternate sign out" << "arrow" << "exit" << "leave" << "log out" << "logout" << "sign-out");
addIcon(0xf012, false, QStringList() << "signal" << "bars" << "graph" << "online" << "status");
addIcon(0xf5b7, false, QStringList() << "signature" << "John Hancock" << "cursive" << "name" << "writing");
addIcon(0xf0e8, false, QStringList() << "sitemap" << "directory" << "hierarchy" << "ia" << "information architecture" << "organization");
addIcon(0xf54c, false, QStringList() << "skull" << "bones" << "skeleton" << "yorick");
addIcon(0xf1de, false, QStringList() << "horizontal sliders" << "settings" << "sliders");
addIcon(0xf118, false, QStringList() << "smiling face" << "approve" << "emoticon" << "face" << "happy" << "rating" << "satisfied");
addIcon(0xf5b8, false, QStringList() << "beaming face with smiling eyes" << "emoticon" << "face" << "happy");
addIcon(0xf4da, false, QStringList() << "winking face" << "emoticon" << "face" << "happy");
addIcon(0xf48d, false, QStringList() << "smoking" << "cigarette" << "nicotine" << "smoking status");
addIcon(0xf54d, false, QStringList() << "smoking ban" << "no smoking" << "non-smoking");
addIcon(0xf2dc, false, QStringList() << "snowflake");
addIcon(0xf5ba, false, QStringList() << "solar panel" << "clean" << "eco-friendly" << "energy" << "green" << "sun");
addIcon(0xf0dc, false, QStringList() << "sort" << "order");
addIcon(0xf15d, false, QStringList() << "sort alpha down" << "sort-alpha-asc");
addIcon(0xf15e, false, QStringList() << "sort alpha up" << "sort-alpha-desc");
addIcon(0xf160, false, QStringList() << "sort amount down" << "sort-amount-asc");
addIcon(0xf161, false, QStringList() << "sort amount up" << "sort-amount-desc");
addIcon(0xf0dd, false, QStringList() << "sort down (descending)" << "arrow" << "descending" << "sort-desc");
addIcon(0xf162, false, QStringList() << "sort numeric down" << "numbers" << "sort-numeric-asc");
addIcon(0xf163, false, QStringList() << "sort numeric up" << "numbers" << "sort-numeric-desc");
addIcon(0xf0de, false, QStringList() << "sort up (ascending)" << "arrow" << "ascending" << "sort-asc");
addIcon(0xf5bb, false, QStringList() << "spa" << "mindfullness" << "plant" << "wellness");
addIcon(0xf197, false, QStringList() << "space shuttle" << "astronaut" << "machine" << "nasa" << "rocket" << "transportation");
addIcon(0xf110, false, QStringList() << "spinner" << "loading" << "progress");
addIcon(0xf5bc, false, QStringList() << "splotch");
addIcon(0xf5bd, false, QStringList() << "spray can");
addIcon(0xf0c8, false, QStringList() << "square" << "block" << "box");
addIcon(0xf45c, false, QStringList() << "square full");
addIcon(0xf5bf, false, QStringList() << "stamp");
addIcon(0xf005, false, QStringList() << "star" << "achievement" << "award" << "favorite" << "important" << "night" << "rating" << "score");
addIcon(0xf089, false, QStringList() << "star-half" << "achievement" << "award" << "rating" << "score" << "star-half-empty" << "star-half-full");
addIcon(0xf5c0, false, QStringList() << "alternate star half" << "achievement" << "award" << "rating" << "score" << "star-half-empty" << "star-half-full");
addIcon(0xf621, false, QStringList() << "star of-life");
addIcon(0xf048, false, QStringList() << "step-backward" << "beginning" << "first" << "previous" << "rewind" << "start");
addIcon(0xf051, false, QStringList() << "step-forward" << "end" << "last" << "next");
addIcon(0xf0f1, false, QStringList() << "stethoscope");
addIcon(0xf249, false, QStringList() << "sticky note");
addIcon(0xf04d, false, QStringList() << "stop" << "block" << "box" << "square");
addIcon(0xf28d, false, QStringList() << "stop circle");
addIcon(0xf2f2, false, QStringList() << "stopwatch" << "time");
addIcon(0xf54e, false, QStringList() << "store");
addIcon(0xf54f, false, QStringList() << "alternate store");
addIcon(0xf550, false, QStringList() << "stream");
addIcon(0xf21d, false, QStringList() << "street view" << "map");
addIcon(0xf0cc, false, QStringList() << "strikethrough");
addIcon(0xf551, false, QStringList() << "stroopwafel" << "dessert" << "food" << "sweets" << "waffle");
addIcon(0xf12c, false, QStringList() << "subscript");
addIcon(0xf239, false, QStringList() << "subway" << "machine" << "railway" << "train" << "transportation" << "vehicle");
addIcon(0xf0f2, false, QStringList() << "suitcase" << "baggage" << "luggage" << "move" << "suitcase" << "travel" << "trip");
addIcon(0xf5c1, false, QStringList() << "suitcase rolling");
addIcon(0xf185, false, QStringList() << "sun" << "brighten" << "contrast" << "day" << "lighter" << "weather");
addIcon(0xf12b, false, QStringList() << "superscript" << "exponential");
addIcon(0xf5c2, false, QStringList() << "hushed face" << "emoticon" << "face" << "shocked");
addIcon(0xf5c3, false, QStringList() << "swatchbook");
addIcon(0xf5c4, false, QStringList() << "swimmer" << "athlete" << "head" << "man" << "person" << "water");
addIcon(0xf5c5, false, QStringList() << "swimming pool" << "ladder" << "recreation" << "water");
addIcon(0xf021, false, QStringList() << "sync" << "exchange" << "refresh" << "reload" << "rotate" << "swap");
addIcon(0xf2f1, false, QStringList() << "alternate sync" << "refresh" << "reload" << "rotate");
addIcon(0xf48e, false, QStringList() << "syringe" << "immunizations" << "needle");
addIcon(0xf0ce, false, QStringList() << "table" << "data" << "excel" << "spreadsheet");
addIcon(0xf45d, false, QStringList() << "table tennis");
addIcon(0xf10a, false, QStringList() << "tablet" << "apple" << "device" << "ipad" << "kindle" << "screen");
addIcon(0xf3fa, false, QStringList() << "alternate tablet" << "apple" << "device" << "ipad" << "kindle" << "screen");
addIcon(0xf490, false, QStringList() << "tablets" << "drugs" << "medicine");
addIcon(0xf3fd, false, QStringList() << "alternate tachometer" << "dashboard" << "tachometer");
addIcon(0xf02b, false, QStringList() << "tag" << "label");
addIcon(0xf02c, false, QStringList() << "tags" << "labels");
addIcon(0xf4db, false, QStringList() << "tape");
addIcon(0xf0ae, false, QStringList() << "tasks" << "downloading" << "downloads" << "loading" << "progress" << "settings");
addIcon(0xf1ba, false, QStringList() << "taxi" << "cab" << "cabbie" << "car" << "car service" << "lyft" << "machine" << "transportation" << "uber" << "vehicle");
addIcon(0xf62e, false, QStringList() << "teeth");
addIcon(0xf62f, false, QStringList() << "teeth open");
addIcon(0xf120, false, QStringList() << "terminal" << "code" << "command" << "console" << "prompt");
addIcon(0xf034, false, QStringList() << "text-height");
addIcon(0xf035, false, QStringList() << "text-width");
addIcon(0xf00a, false, QStringList() << "th" << "blocks" << "boxes" << "grid" << "squares");
addIcon(0xf009, false, QStringList() << "th-large" << "blocks" << "boxes" << "grid" << "squares");
addIcon(0xf00b, false, QStringList() << "th-list" << "checklist" << "completed" << "done" << "finished" << "ol" << "todo" << "ul");
addIcon(0xf630, false, QStringList() << "theater masks");
addIcon(0xf491, false, QStringList() << "thermometer" << "fever" << "temperature");
addIcon(0xf2cb, false, QStringList() << "thermometer empty" << "status");
addIcon(0xf2c7, false, QStringList() << "thermometer full" << "status");
addIcon(0xf2c9, false, QStringList() << "thermometer 1/2 full" << "status");
addIcon(0xf2ca, false, QStringList() << "thermometer 1/4 full" << "status");
addIcon(0xf2c8, false, QStringList() << "thermometer 3/4 full" << "status");
addIcon(0xf165, false, QStringList() << "thumbs-down" << "disagree" << "disapprove" << "dislike" << "hand" << "thumbs-o-down");
addIcon(0xf164, false, QStringList() << "thumbs-up" << "agree" << "approve" << "favorite" << "hand" << "like" << "ok" << "okay" << "success" << "thumbs-o-up" << "yes" << "you got it dude");
addIcon(0xf08d, false, QStringList() << "thumbtack" << "coordinates" << "location" << "marker" << "pin" << "thumb-tack");
addIcon(0xf3ff, false, QStringList() << "alternate ticket" << "ticket");
addIcon(0xf00d, false, QStringList() << "times" << "close" << "cross" << "error" << "exit" << "incorrect" << "notice" << "notification" << "notify" << "problem" << "wrong" << "x");
addIcon(0xf057, false, QStringList() << "times circle" << "close" << "cross" << "exit" << "incorrect" << "notice" << "notification" << "notify" << "problem" << "wrong" << "x");
addIcon(0xf043, false, QStringList() << "tint" << "drop" << "droplet" << "raindrop" << "waterdrop");
addIcon(0xf5c7, false, QStringList() << "tint slash");
addIcon(0xf5c8, false, QStringList() << "tired face" << "emoticon" << "face" << "grumpy");
addIcon(0xf204, false, QStringList() << "toggle off" << "switch");
addIcon(0xf205, false, QStringList() << "toggle on" << "switch");
addIcon(0xf552, false, QStringList() << "toolbox" << "admin" << "container" << "fix" << "repair" << "settings" << "tools");
addIcon(0xf5c9, false, QStringList() << "tooth" << "bicuspid" << "dental" << "molar" << "mouth" << "teeth");
addIcon(0xf25c, false, QStringList() << "trademark");
addIcon(0xf637, false, QStringList() << "traffic light");
addIcon(0xf238, false, QStringList() << "train" << "bullet" << "locomotive" << "railway");
addIcon(0xf224, false, QStringList() << "transgender" << "intersex");
addIcon(0xf225, false, QStringList() << "alternate transgender");
addIcon(0xf1f8, false, QStringList() << "trash" << "delete" << "garbage" << "hide" << "remove");
addIcon(0xf2ed, false, QStringList() << "alternate trash" << "delete" << "garbage" << "hide" << "remove" << "trash" << "trash-o");
addIcon(0xf1bb, false, QStringList() << "tree");
addIcon(0xf091, false, QStringList() << "trophy" << "achievement" << "award" << "cup" << "game" << "winner");
addIcon(0xf0d1, false, QStringList() << "truck" << "delivery" << "shipping");
addIcon(0xf4de, false, QStringList() << "truck loading");
addIcon(0xf63b, false, QStringList() << "truck monster");
addIcon(0xf4df, false, QStringList() << "truck moving");
addIcon(0xf63c, false, QStringList() << "truck side");
addIcon(0xf553, false, QStringList() << "t-shirt" << "cloth" << "clothing");
addIcon(0xf1e4, false, QStringList() << "tty");
addIcon(0xf26c, false, QStringList() << "television" << "computer" << "display" << "monitor" << "television");
addIcon(0xf0e9, false, QStringList() << "umbrella" << "protection" << "rain");
addIcon(0xf5ca, false, QStringList() << "umbrella beach" << "protection" << "recreation" << "sun");
addIcon(0xf0cd, false, QStringList() << "underline");
addIcon(0xf0e2, false, QStringList() << "undo" << "back" << "control z" << "exchange" << "oops" << "return" << "rotate" << "swap");
addIcon(0xf2ea, false, QStringList() << "alternate undo" << "back" << "control z" << "exchange" << "oops" << "return" << "swap");
addIcon(0xf29a, false, QStringList() << "universal access");
addIcon(0xf19c, false, QStringList() << "university" << "bank" << "institution");
addIcon(0xf127, false, QStringList() << "unlink" << "chain" << "chain-broken" << "remove");
addIcon(0xf09c, false, QStringList() << "unlock" << "admin" << "lock" << "password" << "protect");
addIcon(0xf13e, false, QStringList() << "alternate unlock" << "admin" << "lock" << "password" << "protect");
addIcon(0xf093, false, QStringList() << "upload" << "export" << "publish");
addIcon(0xf007, false, QStringList() << "user" << "account" << "avatar" << "head" << "man" << "person" << "profile");
addIcon(0xf406, false, QStringList() << "alternate user" << "account" << "avatar" << "head" << "man" << "person" << "profile");
addIcon(0xf4fa, false, QStringList() << "alternate user slash");
addIcon(0xf4fb, false, QStringList() << "user astronaut" << "avatar" << "clothing" << "cosmonaut" << "space" << "suit");
addIcon(0xf4fc, false, QStringList() << "user check");
addIcon(0xf2bd, false, QStringList() << "user circle" << "account" << "avatar" << "head" << "man" << "person" << "profile");
addIcon(0xf4fd, false, QStringList() << "user clock");
addIcon(0xf4fe, false, QStringList() << "user cog");
addIcon(0xf4ff, false, QStringList() << "user edit");
addIcon(0xf500, false, QStringList() << "user friends");
addIcon(0xf501, false, QStringList() << "user graduate" << "cap" << "clothing" << "commencement" << "gown" << "graduation" << "student");
addIcon(0xf502, false, QStringList() << "user lock");
addIcon(0xf0f0, false, QStringList() << "user-md" << "doctor" << "job" << "medical" << "nurse" << "occupation" << "profile");
addIcon(0xf503, false, QStringList() << "user minus");
addIcon(0xf504, false, QStringList() << "user ninja" << "assassin" << "avatar" << "dangerous" << "sneaky");
addIcon(0xf234, false, QStringList() << "add user" << "sign up" << "signup");
addIcon(0xf21b, false, QStringList() << "user secret" << "clothing" << "coat" << "hat" << "incognito" << "privacy" << "spy" << "whisper");
addIcon(0xf505, false, QStringList() << "user shield");
addIcon(0xf506, false, QStringList() << "user slash");
addIcon(0xf507, false, QStringList() << "user tag");
addIcon(0xf508, false, QStringList() << "user tie" << "avatar" << "business" << "clothing" << "formal");
addIcon(0xf235, false, QStringList() << "remove user");
addIcon(0xf0c0, false, QStringList() << "users" << "people" << "persons" << "profiles");
addIcon(0xf509, false, QStringList() << "users cog");
addIcon(0xf2e5, false, QStringList() << "utensil spoon" << "spoon");
addIcon(0xf2e7, false, QStringList() << "utensils" << "cutlery" << "dinner" << "eat" << "food" << "knife" << "restaurant" << "spoon");
addIcon(0xf5cb, false, QStringList() << "vector square" << "anchors" << "lines" << "object");
addIcon(0xf221, false, QStringList() << "venus" << "female");
addIcon(0xf226, false, QStringList() << "venus double");
addIcon(0xf228, false, QStringList() << "venus mars");
addIcon(0xf492, false, QStringList() << "vial" << "test tube");
addIcon(0xf493, false, QStringList() << "vials" << "lab results" << "test tubes");
addIcon(0xf03d, false, QStringList() << "video" << "camera" << "film" << "movie" << "record" << "video-camera");
addIcon(0xf4e2, false, QStringList() << "video slash");
addIcon(0xf45f, false, QStringList() << "volleyball ball");
addIcon(0xf027, false, QStringList() << "volume-down" << "audio" << "lower" << "music" << "quieter" << "sound" << "speaker");
addIcon(0xf026, false, QStringList() << "volume-off" << "audio" << "music" << "mute" << "sound");
addIcon(0xf028, false, QStringList() << "volume-up" << "audio" << "higher" << "louder" << "music" << "sound" << "speaker");
addIcon(0xf554, false, QStringList() << "walking");
addIcon(0xf555, false, QStringList() << "wallet");
addIcon(0xf494, false, QStringList() << "warehouse");
addIcon(0xf496, false, QStringList() << "weight" << "measurement" << "scale" << "weight");
addIcon(0xf5cd, false, QStringList() << "hanging weight" << "anvil" << "heavy" << "measurement");
addIcon(0xf193, false, QStringList() << "wheelchair" << "handicap" << "person");
addIcon(0xf1eb, false, QStringList() << "wifi");
addIcon(0xf410, false, QStringList() << "window close");
addIcon(0xf2d0, false, QStringList() << "window maximize");
addIcon(0xf2d1, false, QStringList() << "window minimize");
addIcon(0xf2d2, false, QStringList() << "window restore");
addIcon(0xf4e3, false, QStringList() << "wine glass");
addIcon(0xf5ce, false, QStringList() << "wine glass-alt");
addIcon(0xf159, false, QStringList() << "won sign" << "krw" << "krw");
addIcon(0xf0ad, false, QStringList() << "wrench" << "fix" << "settings" << "spanner" << "tool" << "update");
addIcon(0xf497, false, QStringList() << "x-ray" << "radiological images" << "radiology");
addIcon(0xf157, false, QStringList() << "yen sign" << "jpy" << "jpy");
addIcon(0xf26e, true, QStringList() << "500px");
addIcon(0xf368, true, QStringList() << "accessible icon" << "accessibility" << "handicap" << "person" << "wheelchair" << "wheelchair-alt");
addIcon(0xf369, true, QStringList() << "accusoft");
addIcon(0xf170, true, QStringList() << "app.net");
addIcon(0xf36a, true, QStringList() << "adversal");
addIcon(0xf36b, true, QStringList() << "affiliatetheme");
addIcon(0xf36c, true, QStringList() << "algolia");
addIcon(0xf270, true, QStringList() << "amazon");
addIcon(0xf42c, true, QStringList() << "amazon pay");
addIcon(0xf36d, true, QStringList() << "amilia");
addIcon(0xf17b, true, QStringList() << "android" << "robot");
addIcon(0xf209, true, QStringList() << "angellist");
addIcon(0xf36e, true, QStringList() << "angry creative");
addIcon(0xf420, true, QStringList() << "angular");
addIcon(0xf36f, true, QStringList() << "app store");
addIcon(0xf370, true, QStringList() << "ios app store");
addIcon(0xf371, true, QStringList() << "apper systems ab");
addIcon(0xf179, true, QStringList() << "apple" << "food" << "fruit" << "osx");
addIcon(0xf415, true, QStringList() << "apple pay");
addIcon(0xf372, true, QStringList() << "asymmetrik, ltd.");
addIcon(0xf373, true, QStringList() << "audible");
addIcon(0xf41c, true, QStringList() << "autoprefixer");
addIcon(0xf374, true, QStringList() << "avianex");
addIcon(0xf421, true, QStringList() << "aviato");
addIcon(0xf375, true, QStringList() << "amazon web services (aws)");
addIcon(0xf2d5, true, QStringList() << "bandcamp");
addIcon(0xf1b4, true, QStringList() << "behance");
addIcon(0xf1b5, true, QStringList() << "behance square");
addIcon(0xf378, true, QStringList() << "bimobject");
addIcon(0xf171, true, QStringList() << "bitbucket" << "bitbucket-square" << "git");
addIcon(0xf379, true, QStringList() << "bitcoin");
addIcon(0xf37a, true, QStringList() << "bity");
addIcon(0xf27e, true, QStringList() << "font awesome black tie");
addIcon(0xf37b, true, QStringList() << "blackberry");
addIcon(0xf37c, true, QStringList() << "blogger");
addIcon(0xf37d, true, QStringList() << "blogger b");
addIcon(0xf293, true, QStringList() << "bluetooth");
addIcon(0xf294, true, QStringList() << "bluetooth");
addIcon(0xf15a, true, QStringList() << "btc");
addIcon(0xf37f, true, QStringList() << "b\u00fcrom\u00f6bel-experte gmbh & co. kg.");
addIcon(0xf20d, true, QStringList() << "buysellads");
addIcon(0xf42d, true, QStringList() << "amazon pay credit card");
addIcon(0xf1f3, true, QStringList() << "american express credit card" << "amex");
addIcon(0xf416, true, QStringList() << "apple pay credit card");
addIcon(0xf24c, true, QStringList() << "diner's club credit card");
addIcon(0xf1f2, true, QStringList() << "discover credit card");
addIcon(0xf24b, true, QStringList() << "jcb credit card");
addIcon(0xf1f1, true, QStringList() << "mastercard credit card");
addIcon(0xf1f4, true, QStringList() << "paypal credit card");
addIcon(0xf1f5, true, QStringList() << "stripe credit card");
addIcon(0xf1f0, true, QStringList() << "visa credit card");
addIcon(0xf380, true, QStringList() << "centercode");
addIcon(0xf268, true, QStringList() << "chrome" << "browser");
addIcon(0xf383, true, QStringList() << "cloudscale.ch");
addIcon(0xf384, true, QStringList() << "cloudsmith");
addIcon(0xf385, true, QStringList() << "cloudversify");
addIcon(0xf1cb, true, QStringList() << "codepen");
addIcon(0xf284, true, QStringList() << "codie pie");
addIcon(0xf20e, true, QStringList() << "connect develop");
addIcon(0xf26d, true, QStringList() << "contao");
addIcon(0xf388, true, QStringList() << "cpanel");
addIcon(0xf25e, true, QStringList() << "creative commons");
addIcon(0xf4e7, true, QStringList() << "creative commons attribution");
addIcon(0xf4e8, true, QStringList() << "creative commons noncommercial");
addIcon(0xf4e9, true, QStringList() << "creative commons noncommercial (euro sign)");
addIcon(0xf4ea, true, QStringList() << "creative commons noncommercial (yen sign)");
addIcon(0xf4eb, true, QStringList() << "creative commons no derivative works");
addIcon(0xf4ec, true, QStringList() << "creative commons public domain");
addIcon(0xf4ed, true, QStringList() << "creative commons public domain alternate");
addIcon(0xf4ee, true, QStringList() << "creative commons remix");
addIcon(0xf4ef, true, QStringList() << "creative commons share alike");
addIcon(0xf4f0, true, QStringList() << "creative commons sampling");
addIcon(0xf4f1, true, QStringList() << "creative commons sampling +");
addIcon(0xf4f2, true, QStringList() << "creative commons share");
addIcon(0xf13c, true, QStringList() << "css 3 logo" << "code");
addIcon(0xf38b, true, QStringList() << "alternate css3 logo");
addIcon(0xf38c, true, QStringList() << "cuttlefish");
addIcon(0xf38d, true, QStringList() << "dungeons & dragons");
addIcon(0xf210, true, QStringList() << "dashcube");
addIcon(0xf1a5, true, QStringList() << "delicious logo");
addIcon(0xf38e, true, QStringList() << "deploy.dog");
addIcon(0xf38f, true, QStringList() << "deskpro");
addIcon(0xf1bd, true, QStringList() << "deviantart");
addIcon(0xf1a6, true, QStringList() << "digg logo");
addIcon(0xf391, true, QStringList() << "digital ocean");
addIcon(0xf392, true, QStringList() << "discord");
addIcon(0xf393, true, QStringList() << "discourse");
addIcon(0xf394, true, QStringList() << "dochub");
addIcon(0xf395, true, QStringList() << "docker");
addIcon(0xf396, true, QStringList() << "draft2digital");
addIcon(0xf17d, true, QStringList() << "dribbble");
addIcon(0xf397, true, QStringList() << "dribbble square");
addIcon(0xf16b, true, QStringList() << "dropbox");
addIcon(0xf1a9, true, QStringList() << "drupal logo");
addIcon(0xf399, true, QStringList() << "dyalog");
addIcon(0xf39a, true, QStringList() << "earlybirds");
addIcon(0xf4f4, true, QStringList() << "ebay");
addIcon(0xf282, true, QStringList() << "edge browser" << "browser" << "ie");
addIcon(0xf430, true, QStringList() << "elementor");
addIcon(0xf5f1, true, QStringList() << "ello");
addIcon(0xf423, true, QStringList() << "ember");
addIcon(0xf1d1, true, QStringList() << "galactic empire");
addIcon(0xf299, true, QStringList() << "envira gallery" << "leaf");
addIcon(0xf39d, true, QStringList() << "erlang");
addIcon(0xf42e, true, QStringList() << "ethereum");
addIcon(0xf2d7, true, QStringList() << "etsy");
addIcon(0xf23e, true, QStringList() << "expeditedssl");
addIcon(0xf09a, true, QStringList() << "facebook" << "facebook-official" << "social network");
addIcon(0xf39e, true, QStringList() << "facebook f" << "facebook");
addIcon(0xf39f, true, QStringList() << "facebook messenger");
addIcon(0xf082, true, QStringList() << "facebook square" << "social network");
addIcon(0xf269, true, QStringList() << "firefox" << "browser");
addIcon(0xf2b0, true, QStringList() << "first order");
addIcon(0xf50a, true, QStringList() << "alternate first order");
addIcon(0xf3a1, true, QStringList() << "firstdraft");
addIcon(0xf16e, true, QStringList() << "flickr");
addIcon(0xf44d, true, QStringList() << "flipboard");
addIcon(0xf417, true, QStringList() << "fly");
addIcon(0xf2b4, true, QStringList() << "font awesome" << "meanpath");
addIcon(0xf35c, true, QStringList() << "alternate font awesome");
addIcon(0xf425, true, QStringList() << "font awesome flag");
addIcon(0xf4e6, true, QStringList() << "font awesome full logo");
addIcon(0xf280, true, QStringList() << "fonticons");
addIcon(0xf3a2, true, QStringList() << "fonticons fi");
addIcon(0xf286, true, QStringList() << "fort awesome" << "castle");
addIcon(0xf3a3, true, QStringList() << "alternate fort awesome" << "castle");
addIcon(0xf211, true, QStringList() << "forumbee");
addIcon(0xf180, true, QStringList() << "foursquare");
addIcon(0xf2c5, true, QStringList() << "free code camp");
addIcon(0xf3a4, true, QStringList() << "freebsd");
addIcon(0xf50b, true, QStringList() << "fulcrum");
addIcon(0xf50c, true, QStringList() << "galactic republic");
addIcon(0xf50d, true, QStringList() << "galactic senate");
addIcon(0xf265, true, QStringList() << "get pocket");
addIcon(0xf260, true, QStringList() << "gg currency");
addIcon(0xf261, true, QStringList() << "gg currency circle");
addIcon(0xf1d3, true, QStringList() << "git");
addIcon(0xf1d2, true, QStringList() << "git square");
addIcon(0xf09b, true, QStringList() << "github" << "octocat");
addIcon(0xf113, true, QStringList() << "alternate github" << "octocat");
addIcon(0xf092, true, QStringList() << "github square" << "octocat");
addIcon(0xf3a6, true, QStringList() << "gitkraken");
addIcon(0xf296, true, QStringList() << "gitlab" << "Axosoft");
addIcon(0xf426, true, QStringList() << "gitter");
addIcon(0xf2a5, true, QStringList() << "glide");
addIcon(0xf2a6, true, QStringList() << "glide g");
addIcon(0xf3a7, true, QStringList() << "gofore");
addIcon(0xf3a8, true, QStringList() << "goodreads");
addIcon(0xf3a9, true, QStringList() << "goodreads g");
addIcon(0xf1a0, true, QStringList() << "google logo");
addIcon(0xf3aa, true, QStringList() << "google drive");
addIcon(0xf3ab, true, QStringList() << "google play");
addIcon(0xf2b3, true, QStringList() << "google plus" << "google-plus-circle" << "google-plus-official");
addIcon(0xf0d5, true, QStringList() << "google plus g" << "google-plus" << "social network");
addIcon(0xf0d4, true, QStringList() << "google plus square" << "social network");
addIcon(0xf1ee, true, QStringList() << "google wallet");
addIcon(0xf184, true, QStringList() << "gratipay (gittip)" << "favorite" << "heart" << "like" << "love");
addIcon(0xf2d6, true, QStringList() << "grav");
addIcon(0xf3ac, true, QStringList() << "gripfire, inc.");
addIcon(0xf3ad, true, QStringList() << "grunt");
addIcon(0xf3ae, true, QStringList() << "gulp");
addIcon(0xf1d4, true, QStringList() << "hacker news");
addIcon(0xf3af, true, QStringList() << "hacker news square");
addIcon(0xf5f7, true, QStringList() << "hackerrank");
addIcon(0xf452, true, QStringList() << "hips");
addIcon(0xf3b0, true, QStringList() << "hireahelper");
addIcon(0xf427, true, QStringList() << "hooli");
addIcon(0xf592, true, QStringList() << "hornbill");
addIcon(0xf3b1, true, QStringList() << "hotjar");
addIcon(0xf27c, true, QStringList() << "houzz");
addIcon(0xf13b, true, QStringList() << "html 5 logo");
addIcon(0xf3b2, true, QStringList() << "hubspot");
addIcon(0xf2d8, true, QStringList() << "imdb");
addIcon(0xf16d, true, QStringList() << "instagram");
addIcon(0xf26b, true, QStringList() << "internet-explorer" << "browser" << "ie");
addIcon(0xf208, true, QStringList() << "ioxhost");
addIcon(0xf3b4, true, QStringList() << "itunes");
addIcon(0xf3b5, true, QStringList() << "itunes note");
addIcon(0xf4e4, true, QStringList() << "java");
addIcon(0xf50e, true, QStringList() << "jedi order");
addIcon(0xf3b6, true, QStringList() << "jenkis");
addIcon(0xf3b7, true, QStringList() << "joget");
addIcon(0xf1aa, true, QStringList() << "joomla logo");
addIcon(0xf3b8, true, QStringList() << "javascript (js)");
addIcon(0xf3b9, true, QStringList() << "javascript (js) square");
addIcon(0xf1cc, true, QStringList() << "jsfiddle");
addIcon(0xf5fa, true, QStringList() << "kaggle");
addIcon(0xf4f5, true, QStringList() << "keybase");
addIcon(0xf3ba, true, QStringList() << "keycdn");
addIcon(0xf3bb, true, QStringList() << "kickstarter");
addIcon(0xf3bc, true, QStringList() << "kickstarter k");
addIcon(0xf42f, true, QStringList() << "korvue");
addIcon(0xf3bd, true, QStringList() << "laravel");
addIcon(0xf202, true, QStringList() << "last.fm");
addIcon(0xf203, true, QStringList() << "last.fm square");
addIcon(0xf212, true, QStringList() << "leanpub");
addIcon(0xf41d, true, QStringList() << "less");
addIcon(0xf3c0, true, QStringList() << "line");
addIcon(0xf08c, true, QStringList() << "linkedin" << "linkedin-square");
addIcon(0xf0e1, true, QStringList() << "linkedin in" << "linkedin");
addIcon(0xf2b8, true, QStringList() << "linode");
addIcon(0xf17c, true, QStringList() << "linux" << "tux");
addIcon(0xf3c3, true, QStringList() << "lyft");
addIcon(0xf3c4, true, QStringList() << "magento");
addIcon(0xf59e, true, QStringList() << "mailchimp");
addIcon(0xf50f, true, QStringList() << "mandalorian");
addIcon(0xf60f, true, QStringList() << "markdown");
addIcon(0xf4f6, true, QStringList() << "mastodon");
addIcon(0xf136, true, QStringList() << "maxcdn");
addIcon(0xf3c6, true, QStringList() << "medapps");
addIcon(0xf23a, true, QStringList() << "medium");
addIcon(0xf3c7, true, QStringList() << "medium m");
addIcon(0xf3c8, true, QStringList() << "mrt");
addIcon(0xf2e0, true, QStringList() << "meetup");
addIcon(0xf5a3, true, QStringList() << "megaport");
addIcon(0xf3ca, true, QStringList() << "microsoft");
addIcon(0xf3cb, true, QStringList() << "mix");
addIcon(0xf289, true, QStringList() << "mixcloud");
addIcon(0xf3cc, true, QStringList() << "mizuni");
addIcon(0xf285, true, QStringList() << "modx");
addIcon(0xf3d0, true, QStringList() << "monero");
addIcon(0xf3d2, true, QStringList() << "napster");
addIcon(0xf612, true, QStringList() << "neos");
addIcon(0xf5a8, true, QStringList() << "nimblr");
addIcon(0xf418, true, QStringList() << "nintendo switch");
addIcon(0xf419, true, QStringList() << "node.js");
addIcon(0xf3d3, true, QStringList() << "node.js js");
addIcon(0xf3d4, true, QStringList() << "npm");
addIcon(0xf3d5, true, QStringList() << "ns8");
addIcon(0xf3d6, true, QStringList() << "nutritionix");
addIcon(0xf263, true, QStringList() << "odnoklassniki");
addIcon(0xf264, true, QStringList() << "odnoklassniki square");
addIcon(0xf510, true, QStringList() << "old republic");
addIcon(0xf23d, true, QStringList() << "opencart");
addIcon(0xf19b, true, QStringList() << "openid");
addIcon(0xf26a, true, QStringList() << "opera");
addIcon(0xf23c, true, QStringList() << "optin monster");
addIcon(0xf41a, true, QStringList() << "open source initiative");
addIcon(0xf3d7, true, QStringList() << "page4 corporation");
addIcon(0xf18c, true, QStringList() << "pagelines" << "eco" << "leaf" << "leaves" << "nature" << "plant" << "tree");
addIcon(0xf3d8, true, QStringList() << "palfed");
addIcon(0xf3d9, true, QStringList() << "patreon");
addIcon(0xf1ed, true, QStringList() << "paypal");
addIcon(0xf3da, true, QStringList() << "periscope");
addIcon(0xf3db, true, QStringList() << "phabricator");
addIcon(0xf3dc, true, QStringList() << "phoenix framework");
addIcon(0xf511, true, QStringList() << "phoenix squadron");
addIcon(0xf457, true, QStringList() << "php");
addIcon(0xf2ae, true, QStringList() << "pied piper logo");
addIcon(0xf1a8, true, QStringList() << "alternate pied piper logo");
addIcon(0xf4e5, true, QStringList() << "pied piper-hat" << "clothing");
addIcon(0xf1a7, true, QStringList() << "pied piper pp logo (old)");
addIcon(0xf0d2, true, QStringList() << "pinterest");
addIcon(0xf231, true, QStringList() << "pinterest p");
addIcon(0xf0d3, true, QStringList() << "pinterest square");
addIcon(0xf3df, true, QStringList() << "playstation");
addIcon(0xf288, true, QStringList() << "product hunt");
addIcon(0xf3e1, true, QStringList() << "pushed");
addIcon(0xf3e2, true, QStringList() << "python");
addIcon(0xf1d6, true, QStringList() << "qq");
addIcon(0xf459, true, QStringList() << "quinscape");
addIcon(0xf2c4, true, QStringList() << "quora");
addIcon(0xf4f7, true, QStringList() << "r project");
addIcon(0xf2d9, true, QStringList() << "ravelry");
addIcon(0xf41b, true, QStringList() << "react");
addIcon(0xf4d5, true, QStringList() << "readme");
addIcon(0xf1d0, true, QStringList() << "rebel alliance");
addIcon(0xf3e3, true, QStringList() << "red river");
addIcon(0xf1a1, true, QStringList() << "reddit logo");
addIcon(0xf281, true, QStringList() << "reddit alien");
addIcon(0xf1a2, true, QStringList() << "reddit square");
addIcon(0xf3e4, true, QStringList() << "rendact");
addIcon(0xf18b, true, QStringList() << "renren");
addIcon(0xf3e6, true, QStringList() << "replyd");
addIcon(0xf4f8, true, QStringList() << "researchgate");
addIcon(0xf3e7, true, QStringList() << "resolving");
addIcon(0xf5b2, true, QStringList() << "rev.io");
addIcon(0xf3e8, true, QStringList() << "rocket.chat");
addIcon(0xf3e9, true, QStringList() << "rockrms");
addIcon(0xf267, true, QStringList() << "safari" << "browser");
addIcon(0xf41e, true, QStringList() << "sass");
addIcon(0xf3ea, true, QStringList() << "schlix");
addIcon(0xf28a, true, QStringList() << "scribd");
addIcon(0xf3eb, true, QStringList() << "searchengin");
addIcon(0xf2da, true, QStringList() << "sellcast" << "eercast");
addIcon(0xf213, true, QStringList() << "sellsy");
addIcon(0xf3ec, true, QStringList() << "servicestack");
addIcon(0xf214, true, QStringList() << "shirts in bulk");
addIcon(0xf5b5, true, QStringList() << "shopware");
addIcon(0xf215, true, QStringList() << "simplybuilt");
addIcon(0xf3ee, true, QStringList() << "sistrix");
addIcon(0xf512, true, QStringList() << "sith");
addIcon(0xf216, true, QStringList() << "skyatlas");
addIcon(0xf17e, true, QStringList() << "skype");
addIcon(0xf198, true, QStringList() << "slack logo" << "anchor" << "hash" << "hashtag");
addIcon(0xf3ef, true, QStringList() << "slack hashtag" << "anchor" << "hash" << "hashtag");
addIcon(0xf1e7, true, QStringList() << "slideshare");
addIcon(0xf2ab, true, QStringList() << "snapchat");
addIcon(0xf2ac, true, QStringList() << "snapchat ghost");
addIcon(0xf2ad, true, QStringList() << "snapchat square");
addIcon(0xf1be, true, QStringList() << "soundcloud");
addIcon(0xf3f3, true, QStringList() << "speakap");
addIcon(0xf1bc, true, QStringList() << "spotify");
addIcon(0xf5be, true, QStringList() << "squarespace");
addIcon(0xf18d, true, QStringList() << "stack exchange");
addIcon(0xf16c, true, QStringList() << "stack overflow");
addIcon(0xf3f5, true, QStringList() << "staylinked");
addIcon(0xf1b6, true, QStringList() << "steam");
addIcon(0xf1b7, true, QStringList() << "steam square");
addIcon(0xf3f6, true, QStringList() << "steam symbol");
addIcon(0xf3f7, true, QStringList() << "sticker mule");
addIcon(0xf428, true, QStringList() << "strava");
addIcon(0xf429, true, QStringList() << "stripe");
addIcon(0xf42a, true, QStringList() << "stripe s");
addIcon(0xf3f8, true, QStringList() << "studio vinari");
addIcon(0xf1a4, true, QStringList() << "stumbleupon logo");
addIcon(0xf1a3, true, QStringList() << "stumbleupon circle");
addIcon(0xf2dd, true, QStringList() << "superpowers");
addIcon(0xf3f9, true, QStringList() << "supple");
addIcon(0xf4f9, true, QStringList() << "teamspeak");
addIcon(0xf2c6, true, QStringList() << "telegram");
addIcon(0xf3fe, true, QStringList() << "telegram plane");
addIcon(0xf1d5, true, QStringList() << "tencent weibo");
addIcon(0xf5c6, true, QStringList() << "themeco");
addIcon(0xf2b2, true, QStringList() << "themeisle");
addIcon(0xf513, true, QStringList() << "trade federation");
addIcon(0xf181, true, QStringList() << "trello");
addIcon(0xf262, true, QStringList() << "tripadvisor");
addIcon(0xf173, true, QStringList() << "tumblr");
addIcon(0xf174, true, QStringList() << "tumblr square");
addIcon(0xf1e8, true, QStringList() << "twitch");
addIcon(0xf099, true, QStringList() << "twitter" << "social network" << "tweet");
addIcon(0xf081, true, QStringList() << "twitter square" << "social network" << "tweet");
addIcon(0xf42b, true, QStringList() << "typo3");
addIcon(0xf402, true, QStringList() << "uber");
addIcon(0xf403, true, QStringList() << "uikit");
addIcon(0xf404, true, QStringList() << "uniregistry");
addIcon(0xf405, true, QStringList() << "untappd");
addIcon(0xf287, true, QStringList() << "usb");
addIcon(0xf407, true, QStringList() << "us-sunnah foundation");
addIcon(0xf408, true, QStringList() << "vaadin");
addIcon(0xf237, true, QStringList() << "viacoin");
addIcon(0xf2a9, true, QStringList() << "viadeo");
addIcon(0xf2aa, true, QStringList() << "viadeo square");
addIcon(0xf409, true, QStringList() << "viber");
addIcon(0xf40a, true, QStringList() << "vimeo");
addIcon(0xf194, true, QStringList() << "vimeo square");
addIcon(0xf27d, true, QStringList() << "vimeo" << "vimeo");
addIcon(0xf1ca, true, QStringList() << "vine");
addIcon(0xf189, true, QStringList() << "vk");
addIcon(0xf40b, true, QStringList() << "vnv");
addIcon(0xf41f, true, QStringList() << "vue.js");
addIcon(0xf5cc, true, QStringList() << "weebly");
addIcon(0xf18a, true, QStringList() << "weibo");
addIcon(0xf1d7, true, QStringList() << "weixin (wechat)");
addIcon(0xf232, true, QStringList() << "what's app");
addIcon(0xf40c, true, QStringList() << "what's app square");
addIcon(0xf40d, true, QStringList() << "whmcs");
addIcon(0xf266, true, QStringList() << "wikipedia w");
addIcon(0xf17a, true, QStringList() << "windows" << "microsoft");
addIcon(0xf5cf, true, QStringList() << "wix");
addIcon(0xf514, true, QStringList() << "wolf pack-battalion");
addIcon(0xf19a, true, QStringList() << "wordpress logo");
addIcon(0xf411, true, QStringList() << "wordpress simple");
addIcon(0xf297, true, QStringList() << "wpbeginner");
addIcon(0xf2de, true, QStringList() << "wpexplorer");
addIcon(0xf298, true, QStringList() << "wpforms");
addIcon(0xf412, true, QStringList() << "xbox");
addIcon(0xf168, true, QStringList() << "xing");
addIcon(0xf169, true, QStringList() << "xing square");
addIcon(0xf23b, true, QStringList() << "y combinator");
addIcon(0xf19e, true, QStringList() << "yahoo logo");
addIcon(0xf413, true, QStringList() << "yandex");
addIcon(0xf414, true, QStringList() << "yandex international");
addIcon(0xf1e9, true, QStringList() << "yelp");
addIcon(0xf2b1, true, QStringList() << "yoast");
addIcon(0xf167, true, QStringList() << "youtube" << "film" << "video" << "youtube-play" << "youtube-square");
addIcon(0xf431, true, QStringList() << "youtube square");
addIcon(0xf63f, true, QStringList() << "zhihu");
