#ifndef VERSION_H
#define VERSION_H

#define COPYQ_VERSION_MAJOR 3
#define COPYQ_VERSION_MINOR 3
#define COPYQ_VERSION_PATCH 0

#define COPYQ_STR(x) #x
#define COPYQ_MAKE_VERSION_STR(x, y, z) COPYQ_STR(x) "." COPYQ_STR(y) "." COPYQ_STR(z)
#define COPYQ_BASE_VERSION COPYQ_MAKE_VERSION_STR(COPYQ_VERSION_MAJOR, COPYQ_VERSION_MINOR, COPYQ_VERSION_PATCH)

#ifndef COPYQ_VERSION
#   define COPYQ_VERSION "v" COPYQ_BASE_VERSION
#endif

#endif // VERSION_H
